import { AlgorithmDetailsData } from "./types";
import { algorithmInfo } from "@/components/ControlsPanel";

// We extract standard data, but we can also use the Info from ControlsPanel to fill in gaps.
export const sortingData: Record<string, AlgorithmDetailsData> = {
  bubbleSort: {
    id: "bubbleSort",
    name: "Bubble Sort",
    description: "Bubble Sort is a simple sorting algorithm that repeatedly steps through the list, compares adjacent elements and swaps them if they're in the wrong order.",
    bestCase: "O(n)",
    avgCase: "O(n²)",
    worstCase: "O(n²)",
    timeComplexity: "O(n²)",
    spaceComplexity: "O(1)",
    useCase: "Primarily educational.",
    algorithmFlow: ["Start at the first element (index 0).", "Compare it to the next element (index 1).", "If the first is greater than the second, swap them.", "Move to the next pair (index 1 and 2) and repeat.", "Continue to the end of the array. The largest element will 'bubble' to the last position.", "Repeat the entire process n-1 times for the remaining unsorted portion."],
    codeSnippets: {},
    examples: []
  },
  selectionSort: {
    id: "selectionSort",
    name: "Selection Sort",
    description: "Selection Sort divides the input list into two parts: a sorted portion at the left end and an unsorted portion at the right end.",
    bestCase: "O(n²)",
    avgCase: "O(n²)",
    worstCase: "O(n²)",
    timeComplexity: "O(n²)",
    spaceComplexity: "O(1)",
    useCase: "Highly useful in systems where memory write operations are extremely expensive compared to reads.",
    algorithmFlow: ["Assume the first element is the minimum.", "Scan the rest of the array to find if there is a smaller element.", "If a smaller element is found, update the minimum index.", "At the end of the scan, swap the minimum element with the first element.", "Move the starting boundary one step to the right and repeat until sorted."],
    codeSnippets: {},
    examples: []
  },
  insertionSort: {
    id: "insertionSort",
    name: "Insertion Sort",
    description: "Insertion Sort builds the final sorted array one item at a time. It iterates through the input, removing one element per iteration and finding the location it belongs within the sorted list.",
    bestCase: "O(n)",
    avgCase: "O(n²)",
    worstCase: "O(n²)",
    timeComplexity: "O(n²)",
    spaceComplexity: "O(1)",
    useCase: "Online sorting (sorting data live as it is received).",
    algorithmFlow: ["Assume the first element is already sorted.", "Pick the next element and store it in a temporary variable (key).", "Compare the key with the elements in the sorted portion (moving backwards).", "If a sorted element is greater than the key, shift it one position to the right.", "Repeat until you find an element smaller than the key or reach the beginning.", "Insert the key into the correct position."],
    codeSnippets: {},
    examples: []
  },
  mergeSortWrapper: {
    id: "mergeSortWrapper",
    name: "Merge Sort",
    description: "Merge Sort is a stable, divide-and-conquer sorting algorithm. It divides the input array into two halves, recursively sorts them, and then merges the two sorted halves.",
    bestCase: "O(n log n)",
    avgCase: "O(n log n)",
    worstCase: "O(n log n)",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    useCase: "External sorting (sorting datasets too massive to fit into RAM).",
    algorithmFlow: ["Base case: If the array has 1 or 0 elements, it is already sorted.", "Divide the array down the middle into a 'left' and 'right' half.", "Recursively call Merge Sort on both halves.", "Once the recursive calls return, 'Merge' the two sorted halves back together.", "During merge, maintain two pointers, compare elements from both halves, and place the smaller element into a new temporary array.", "Copy the merged temporary array back into the original array."],
    codeSnippets: {},
    examples: []
  },
  quickSortWrapper: {
    id: "quickSortWrapper",
    name: "Quick Sort",
    description: "Quick Sort is an efficient, in-place, divide-and-conquer sorting algorithm. It works by selecting a 'pivot' element from the array and partitioning the other elements into two sub-arrays.",
    bestCase: "O(n log n)",
    avgCase: "O(n log n)",
    worstCase: "O(n²)",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(log n)",
    useCase: "The default sorting algorithm for primitive types in many languages.",
    algorithmFlow: ["Choose a 'pivot' element from the array.", "Partitioning: Reorder the array so that all elements smaller than the pivot come before it, and all elements greater come after.", "The pivot is now in its final sorted position.", "Recursively apply the above steps to the sub-array of elements with smaller values and separately to the sub-array of elements with greater values."],
    codeSnippets: {},
    examples: []
  },
  heapSort: {
    id: "heapSort",
    name: "Heap Sort",
    description: "Heap Sort involves building a binary heap data structure from the given array and then repeatedly extracting the maximum element from the heap.",
    bestCase: "O(n log n)",
    avgCase: "O(n log n)",
    worstCase: "O(n log n)",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(1)",
    useCase: "Systems with strict memory limits and real-time systems.",
    algorithmFlow: ["Build a Max-Heap from the input array.", "The largest element is now at the root of the heap (index 0).", "Swap the root with the last element of the heap.", "Reduce the heap size by 1 (ignoring the last element which is now sorted).", "Heapify the root to restore the Max-Heap property.", "Repeat until the heap size is 1."],
    codeSnippets: {},
    examples: []
  },
  shellSort: {
    id: "shellSort",
    name: "Shell Sort",
    description: "Generalized insertion sort using decreasing gap sequences.",
    bestCase: "O(n log n)",
    avgCase: "O(n^(4/3))",
    worstCase: "O(n²)",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(1)",
    useCase: "Used in embedded systems or where memory is constrained but better than O(n²) performance is needed.",
    algorithmFlow: ["Start with a large gap size (e.g., n/2).", "Perform a gapped insertion sort for this gap size.", "Reduce the gap size (e.g., divide by 2).", "Repeat until the gap size is 1, which corresponds to a standard insertion sort."],
    codeSnippets: {},
    examples: []
  },
  cocktailSort: {
    id: "cocktailSort",
    name: "Cocktail Sort",
    description: "Bidirectional bubble sort that traverses in both directions alternately.",
    bestCase: "O(n)",
    avgCase: "O(n²)",
    worstCase: "O(n²)",
    timeComplexity: "O(n²)",
    spaceComplexity: "O(1)",
    useCase: "Educational purposes, slightly better than Bubble Sort at moving \"turtles\" (small values at the end of the list).",
    algorithmFlow: ["Traverse from left to right, bubbling the largest value to the end.", "If no swaps occurred, the array is sorted.", "Traverse from right to left, bubbling the smallest value to the start.", "Repeat until no swaps occur in a full pass."],
    codeSnippets: {},
    examples: []
  },
  combSort: {
    id: "combSort",
    name: "Comb Sort",
    description: "Comb Sort improves on Bubble Sort by using a gap larger than 1 to eliminate small values near the end of the array (turtles).",
    bestCase: "O(n log n)",
    avgCase: "O(n²/2^p)",
    worstCase: "O(n²)",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(1)",
    useCase: "Simple to implement variant of Bubble Sort with much better practical performance.",
    algorithmFlow: ["Initialize gap size to n.", "Shrink the gap size by a shrink factor (usually 1.3) in each pass.", "Compare and swap elements that are 'gap' distance apart.", "Continue until gap is 1 and no swaps occur."],
    codeSnippets: {},
    examples: []
  },
  gnomeSort: {
    id: "gnomeSort",
    name: "Gnome Sort",
    description: "Similar to insertion sort but moving elements to their proper place by a series of swaps, similar to how a garden gnome sorts a line of flower pots.",
    bestCase: "O(n)",
    avgCase: "O(n²)",
    worstCase: "O(n²)",
    timeComplexity: "O(n²)",
    spaceComplexity: "O(1)",
    useCase: "Educational, notable for being a single-loop sorting algorithm.",
    algorithmFlow: ["Look at the current pot and the one before it.", "If they are in the right order, step forward.", "If they are in the wrong order, swap them and step backward.", "If at the start of the line, step forward.", "Stop when the end of the line is reached."],
    codeSnippets: {},
    examples: []
  },
  oddEvenSort: {
    id: "oddEvenSort",
    name: "Odd-Even Sort",
    description: "Also known as brick sort, it's a variation of bubble sort originally developed for use on parallel processors with local interconnections.",
    bestCase: "O(n)",
    avgCase: "O(n²)",
    worstCase: "O(n²)",
    timeComplexity: "O(n²)",
    spaceComplexity: "O(1)",
    useCase: "Parallel processing architectures.",
    algorithmFlow: ["Compare and swap all adjacent odd-indexed and even-indexed pairs.", "Compare and swap all adjacent even-indexed and odd-indexed pairs.", "Repeat until the array is fully sorted."],
    codeSnippets: {},
    examples: []
  },
  pancakeSort: {
    id: "pancakeSort",
    name: "Pancake Sort",
    description: "Sorts by repeatedly flipping prefixes of the array to move the maximum elements into place.",
    bestCase: "O(n)",
    avgCase: "O(n²)",
    worstCase: "O(n²)",
    timeComplexity: "O(n²)",
    spaceComplexity: "O(1)",
    useCase: "Mathematical curiosity and routing in parallel networks.",
    algorithmFlow: ["Find the maximum element in the unsorted portion of the array.", "Flip the prefix up to the maximum element, bringing it to the front.", "Flip the entire unsorted portion, moving the maximum element to its correct position at the end.", "Reduce the size of the unsorted portion and repeat."],
    codeSnippets: {},
    examples: []
  },
  bitonicSortWrapper: {
    id: "bitonicSortWrapper",
    name: "Bitonic Sort",
    description: "A parallel algorithm for sorting that creates bitonic sequences and then merges them.",
    bestCase: "O(log² n)",
    avgCase: "O(log² n)",
    worstCase: "O(log² n)",
    timeComplexity: "O(log² n)",
    spaceComplexity: "O(log² n)",
    useCase: "Highly efficient for parallel sorting on hardware like GPUs or FPGAs.",
    algorithmFlow: ["Recursively build a bitonic sequence (one half ascending, one half descending).", "Merge the bitonic sequence by repeatedly comparing elements in the first half with elements in the second half.", "Recursively sort the two halves in the same direction."],
    codeSnippets: {},
    examples: []
  },
  radixSort: {
    id: "radixSort",
    name: "Radix Sort",
    description: "A non-comparative integer sorting algorithm that groups keys by individual digits sharing the same significant position.",
    bestCase: "O(nk)",
    avgCase: "O(nk)",
    worstCase: "O(nk)",
    timeComplexity: "O(nk)",
    spaceComplexity: "O(n+k)",
    useCase: "Sorting extremely large datasets of integers or fixed-length strings.",
    algorithmFlow: ["Find the maximum number to determine the number of digits.", "Perform a stable sorting algorithm (Counting Sort) for each digit.", "Start sorting from the least significant digit (LSD) to the most significant digit (MSD).", "After sorting by all digits, the array is fully sorted."],
    codeSnippets: {},
    examples: []
  },
  stoogeSortWrapper: {
    id: "stoogeSortWrapper",
    name: "Stooge Sort",
    description: "A highly inefficient recursive sorting algorithm that sorts the first 2/3, then the last 2/3, then the first 2/3 again.",
    bestCase: "O(n^2.709)",
    avgCase: "O(n^2.709)",
    worstCase: "O(n^2.709)",
    timeComplexity: "O(n^2.709)",
    spaceComplexity: "O(n)",
    useCase: "Purely educational/humorous, demonstrating bad algorithmic design.",
    algorithmFlow: ["If the value at the start is larger than the value at the end, swap them.", "If there are 3 or more elements in the list, sort the first 2/3 of the list.", "Sort the last 2/3 of the list.", "Sort the first 2/3 of the list again."],
    codeSnippets: {},
    examples: []
  },
  bogoSort: {
    id: "bogoSort",
    name: "Bogo Sort",
    description: "A highly inefficient sorting algorithm that repeatedly shuffles the array until it's sorted.",
    bestCase: "O(n)",
    avgCase: "O(n * n!)",
    worstCase: "O(∞)",
    timeComplexity: "O(∞)",
    spaceComplexity: "O(1)",
    useCase: "A joke algorithm used as an example of how NOT to write a sorting algorithm.",
    algorithmFlow: ["Check if the array is sorted.", "If it is not sorted, randomly shuffle the entire array.", "Repeat until sorted."],
    codeSnippets: {},
    examples: []
  },
  timSort: {
    id: "timSort",
    name: "Tim Sort",
    description: "A hybrid sorting algorithm derived from merge sort and insertion sort, designed to perform well on many kinds of real-world data.",
    bestCase: "O(n)",
    avgCase: "O(n log n)",
    worstCase: "O(n log n)",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    useCase: "The standard sorting algorithm used in Python's sorted() and Java's Arrays.sort() for objects.",
    algorithmFlow: ["Divide the array into small blocks known as runs (usually size 32 or 64).", "Sort these runs using Insertion Sort.", "Merge the sorted runs together using a modified Merge Sort.", "The algorithm exploits existing order (natural runs) in the data."],
    codeSnippets: {},
    examples: []
  },
  introSort: {
    id: "introSort",
    name: "Intro Sort",
    description: "A hybrid sorting algorithm that begins with quicksort and switches to heapsort when the recursion depth exceeds a level based on the number of elements.",
    bestCase: "O(n log n)",
    avgCase: "O(n log n)",
    worstCase: "O(n log n)",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(log n)",
    useCase: "Used in the standard libraries of C++ (std::sort) and C#.",
    algorithmFlow: ["Start with Quick Sort.", "If the recursion depth exceeds 2 * log(n), switch to Heap Sort to guarantee O(n log n) worst-case time.", "For small subarrays, use Insertion Sort to minimize overhead."],
    codeSnippets: {},
    examples: []
  }
};
