export interface CodeImplementation {
  pseudocode: string[];
  javascript: string[];
  typescript?: string[];
  c: string[];
  cpp: string[];
  python: string[];
  java: string[];
  go?: string[];
  php?: string[];
  rust?: string[];
}

export const sortingCodeBlocks: Record<string, CodeImplementation> = {
  bubbleSort: {
    pseudocode: [
      "for i from 0 to n-1:",
      "  for j from 0 to n-i-1:",
      "    if arr[j] > arr[j+1]:",
      "      swap(arr[j], arr[j+1])"
    ],
    javascript: [
      "function bubbleSort(arr) {",
      "  let n = arr.length;",
      "  for (let i = 0; i < n - 1; i++) {",
      "    for (let j = 0; j < n - i - 1; j++) {",
      "      if (arr[j] > arr[j + 1]) {",
      "        [arr[j], arr[j + 1]] = [arr[j + 1], arr[j]];",
      "      }",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def bubble_sort(arr):",
      "    n = len(arr)",
      "    for i in range(n - 1):",
      "        for j in range(n - i - 1):",
      "            if arr[j] > arr[j + 1]:",
      "                arr[j], arr[j + 1] = arr[j + 1], arr[j]",
      "    return arr"
    ],
    java: [
      "public static void bubbleSort(int[] arr) {",
      "    int n = arr.length;",
      "    for (int i = 0; i < n - 1; i++) {",
      "        for (int j = 0; j < n - i - 1; j++) {",
      "            if (arr[j] > arr[j + 1]) {",
      "                int temp = arr[j];",
      "                arr[j] = arr[j + 1];",
      "                arr[j + 1] = temp;",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    cpp: [
      "void bubbleSort(int arr[], int n) {",
      "    for (int i = 0; i < n - 1; i++) {",
      "        for (int j = 0; j < n - i - 1; j++) {",
      "            if (arr[j] > arr[j + 1]) {",
      "                std::swap(arr[j], arr[j + 1]);",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    c: [
      "void bubbleSort(int arr[], int n) {",
      "    for (int i = 0; i < n - 1; i++) {",
      "        for (int j = 0; j < n - i - 1; j++) {",
      "            if (arr[j] > arr[j + 1]) {",
      "                int temp = arr[j];",
      "                arr[j] = arr[j + 1];",
      "                arr[j + 1] = temp;",
      "            }",
      "        }",
      "    }",
      "}"
    ]
  },
  selectionSort: {
    pseudocode: [
      "for i from 0 to n-1:",
      "  min_idx = i",
      "  for j from i+1 to n:",
      "    if arr[j] < arr[min_idx]:",
      "      min_idx = j",
      "  swap(arr[i], arr[min_idx])"
    ],
    javascript: [
      "function selectionSort(arr) {",
      "  let n = arr.length;",
      "  for (let i = 0; i < n - 1; i++) {",
      "    let minIdx = i;",
      "    for (let j = i + 1; j < n; j++) {",
      "      if (arr[j] < arr[minIdx]) minIdx = j;",
      "    }",
      "    [arr[i], arr[minIdx]] = [arr[minIdx], arr[i]];",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def selection_sort(arr):",
      "    n = len(arr)",
      "    for i in range(n - 1):",
      "        min_idx = i",
      "        for j in range(i + 1, n):",
      "            if arr[j] < arr[min_idx]:",
      "                min_idx = j",
      "        arr[i], arr[min_idx] = arr[min_idx], arr[i]",
      "    return arr"
    ],
    java: [
      "public static void selectionSort(int[] arr) {",
      "    int n = arr.length;",
      "    for (int i = 0; i < n - 1; i++) {",
      "        int minIdx = i;",
      "        for (int j = i + 1; j < n; j++) {",
      "            if (arr[j] < arr[minIdx]) minIdx = j;",
      "        }",
      "        int temp = arr[minIdx];",
      "        arr[minIdx] = arr[i];",
      "        arr[i] = temp;",
      "    }",
      "}"
    ],
    cpp: [
      "void selectionSort(int arr[], int n) {",
      "    for (int i = 0; i < n - 1; i++) {",
      "        int minIdx = i;",
      "        for (int j = i + 1; j < n; j++) {",
      "            if (arr[j] < arr[minIdx]) minIdx = j;",
      "        }",
      "        std::swap(arr[i], arr[minIdx]);",
      "    }",
      "}"
    ],
    c: [
      "void selectionSort(int arr[], int n) {",
      "    for (int i = 0; i < n - 1; i++) {",
      "        int minIdx = i;",
      "        for (int j = i + 1; j < n; j++) {",
      "            if (arr[j] < arr[minIdx]) minIdx = j;",
      "        }",
      "        int temp = arr[minIdx];",
      "        arr[minIdx] = arr[i];",
      "        arr[i] = temp;",
      "    }",
      "}"
    ],
    typescript: [
      "function selectionSort(arr: number[]): number[] {",
      "  const n = arr.length;",
      "  for (let i = 0; i < n - 1; i++) {",
      "    let minIdx = i;",
      "    for (let j = i + 1; j < n; j++) {",
      "      if (arr[j] < arr[minIdx]) minIdx = j;",
      "    }",
      "    [arr[i], arr[minIdx]] = [arr[minIdx], arr[i]];",
      "  }",
      "  return arr;",
      "}"
    ],
    go: [
      "func selectionSort(arr []int) {",
      "    n := len(arr)",
      "    for i := 0; i < n-1; i++ {",
      "        minIdx := i",
      "        for j := i + 1; j < n; j++ {",
      "            if arr[j] < arr[minIdx] {",
      "                minIdx = j",
      "            }",
      "        }",
      "        arr[i], arr[minIdx] = arr[minIdx], arr[i]",
      "    }",
      "}"
    ],
    php: [
      "function selectionSort(array &$arr): void {",
      "    $n = count($arr);",
      "    for ($i = 0; $i < $n - 1; $i++) {",
      "        $minIdx = $i;",
      "        for ($j = $i + 1; $j < $n; $j++) {",
      "            if ($arr[$j] < $arr[$minIdx]) {",
      "                $minIdx = $j;",
      "            }",
      "        }",
      "        $temp = $arr[$minIdx];",
      "        $arr[$minIdx] = $arr[$i];",
      "        $arr[$i] = $temp;",
      "    }",
      "}"
    ],
    rust: [
      "fn selection_sort(arr: &mut [i32]) {",
      "    let len = arr.len();",
      "    for i in 0..len {",
      "        let mut min_idx = i;",
      "        for j in (i + 1)..len {",
      "            if arr[j] < arr[min_idx] {",
      "                min_idx = j;",
      "            }",
      "        }",
      "        arr.swap(i, min_idx);",
      "    }",
      "}"
    ]
  },
  insertionSort: {
    pseudocode: [
      "for i from 1 to n-1:",
      "  key = arr[i]",
      "  j = i - 1",
      "  while j >= 0 and arr[j] > key:",
      "    arr[j+1] = arr[j]",
      "    j = j - 1",
      "  arr[j+1] = key"
    ],
    javascript: [
      "function insertionSort(arr) {",
      "  let n = arr.length;",
      "  for (let i = 1; i < n; i++) {",
      "    let key = arr[i];",
      "    let j = i - 1;",
      "    while (j >= 0 && arr[j] > key) {",
      "      arr[j + 1] = arr[j];",
      "      j--;",
      "    }",
      "    arr[j + 1] = key;",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def insertion_sort(arr):",
      "    for i in range(1, len(arr)):",
      "        key = arr[i]",
      "        j = i - 1",
      "        while j >= 0 and arr[j] > key:",
      "            arr[j + 1] = arr[j]",
      "            j -= 1",
      "        arr[j + 1] = key",
      "    return arr"
    ],
    java: [
      "public static void insertionSort(int[] arr) {",
      "    int n = arr.length;",
      "    for (int i = 1; i < n; i++) {",
      "        int key = arr[i];",
      "        int j = i - 1;",
      "        while (j >= 0 && arr[j] > key) {",
      "            arr[j + 1] = arr[j];",
      "            j--;",
      "        }",
      "        arr[j + 1] = key;",
      "    }",
      "}"
    ],
    cpp: [
      "void insertionSort(int arr[], int n) {",
      "    for (int i = 1; i < n; i++) {",
      "        int key = arr[i];",
      "        int j = i - 1;",
      "        while (j >= 0 && arr[j] > key) {",
      "            arr[j + 1] = arr[j];",
      "            j--;",
      "        }",
      "        arr[j + 1] = key;",
      "    }",
      "}"
    ],
    c: [
      "void insertionSort(int arr[], int n) {",
      "    for (int i = 1; i < n; i++) {",
      "        int key = arr[i];",
      "        int j = i - 1;",
      "        while (j >= 0 && arr[j] > key) {",
      "            arr[j + 1] = arr[j];",
      "            j--;",
      "        }",
      "        arr[j + 1] = key;",
      "    }",
      "}"
    ],
    typescript: [
      "function insertionSort(arr: number[]): number[] {",
      "  for (let i = 1; i < arr.length; i++) {",
      "    let key = arr[i];",
      "    let j = i - 1;",
      "    while (j >= 0 && arr[j] > key) {",
      "      arr[j + 1] = arr[j];",
      "      j--;",
      "    }",
      "    arr[j + 1] = key;",
      "  }",
      "  return arr;",
      "}"
    ],
    go: [
      "func insertionSort(arr []int) {",
      "    for i := 1; i < len(arr); i++ {",
      "        key := arr[i]",
      "        j := i - 1",
      "        for j >= 0 && arr[j] > key {",
      "            arr[j+1] = arr[j]",
      "            j--",
      "        }",
      "        arr[j+1] = key",
      "    }",
      "}"
    ],
    php: [
      "function insertionSort(array &$arr): void {",
      "    $n = count($arr);",
      "    for ($i = 1; $i < $n; $i++) {",
      "        $key = $arr[$i];",
      "        $j = $i - 1;",
      "        while ($j >= 0 && $arr[$j] > $key) {",
      "            $arr[$j + 1] = $arr[$j];",
      "            $j--;",
      "        }",
      "        $arr[$j + 1] = $key;",
      "    }",
      "}"
    ],
    rust: [
      "fn insertion_sort(arr: &mut [i32]) {",
      "    for i in 1..arr.len() {",
      "        let key = arr[i];",
      "        let mut j = i;",
      "        while j > 0 && arr[j - 1] > key {",
      "            arr[j] = arr[j - 1];",
      "            j -= 1;",
      "        }",
      "        arr[j] = key;",
      "    }",
      "}"
    ]
  },
  mergeSortWrapper: {
    pseudocode: [
      "function mergeSort(arr):",
      "  if length(arr) <= 1: return arr",
      "  mid = length(arr) / 2",
      "  left = mergeSort(arr[0:mid])",
      "  right = mergeSort(arr[mid:])",
      "  return merge(left, right)"
    ],
    javascript: [
      "function mergeSort(arr) {",
      "  if (arr.length <= 1) return arr;",
      "  const mid = Math.floor(arr.length / 2);",
      "  const left = mergeSort(arr.slice(0, mid));",
      "  const right = mergeSort(arr.slice(mid));",
      "  return merge(left, right);",
      "}"
    ],
    python: [
      "def merge_sort(arr):",
      "    if len(arr) <= 1: return arr",
      "    mid = len(arr) // 2",
      "    left = merge_sort(arr[:mid])",
      "    right = merge_sort(arr[mid:])",
      "    return merge(left, right)"
    ],
    java: [
      "public static void mergeSort(int[] arr, int l, int r) {",
      "    if (l < r) {",
      "        int m = l + (r - l) / 2;",
      "        mergeSort(arr, l, m);",
      "        mergeSort(arr, m + 1, r);",
      "        merge(arr, l, m, r);",
      "    }",
      "}"
    ],
    cpp: [
      "void mergeSort(int arr[], int l, int r) {",
      "    if (l < r) {",
      "        int m = l + (r - l) / 2;",
      "        mergeSort(arr, l, m);",
      "        mergeSort(arr, m + 1, r);",
      "        merge(arr, l, m, r);",
      "    }",
      "}"
    ],
    c: [
      "void mergeSort(int arr[], int l, int r) {",
      "    if (l < r) {",
      "        int m = l + (r - l) / 2;",
      "        mergeSort(arr, l, m);",
      "        mergeSort(arr, m + 1, r);",
      "        merge(arr, l, m, r);",
      "    }",
      "}"
    ],
    typescript: [
      "function mergeSort(arr: number[]): number[] {",
      "  if (arr.length <= 1) return arr;",
      "  const mid = Math.floor(arr.length / 2);",
      "  const left = mergeSort(arr.slice(0, mid));",
      "  const right = mergeSort(arr.slice(mid));",
      "  return merge(left, right);",
      "}"
    ],
    go: [
      "func mergeSort(arr []int) []int {",
      "    if len(arr) <= 1 {",
      "        return arr",
      "    }",
      "    mid := len(arr) / 2",
      "    left := mergeSort(arr[:mid])",
      "    right := mergeSort(arr[mid:])",
      "    return merge(left, right)",
      "}"
    ],
    php: [
      "function mergeSort(array $arr): array {",
      "    if (count($arr) <= 1) return $arr;",
      "    $mid = floor(count($arr) / 2);",
      "    $left = mergeSort(array_slice($arr, 0, $mid));",
      "    $right = mergeSort(array_slice($arr, $mid));",
      "    return merge($left, $right);",
      "}"
    ],
    rust: [
      "fn merge_sort(arr: &mut [i32]) {",
      "    let len = arr.len();",
      "    if len <= 1 {",
      "        return;",
      "    }",
      "    let mid = len / 2;",
      "    merge_sort(&mut arr[..mid]);",
      "    merge_sort(&mut arr[mid..]);",
      "    let mut merged = arr.to_vec();",
      "    merge(&arr[..mid], &arr[mid..], &mut merged);",
      "    arr.copy_from_slice(&merged);",
      "}"
    ]
  },
  quickSortWrapper: {
    pseudocode: [
      "function quickSort(arr, low, high):",
      "  if low < high:",
      "    pi = partition(arr, low, high)",
      "    quickSort(arr, low, pi-1)",
      "    quickSort(arr, pi+1, high)"
    ],
    javascript: [
      "function quickSort(arr, low = 0, high = arr.length - 1) {",
      "  if (low < high) {",
      "    let pi = partition(arr, low, high);",
      "    quickSort(arr, low, pi - 1);",
      "    quickSort(arr, pi + 1, high);",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def quick_sort(arr, low, high):",
      "    if low < high:",
      "        pi = partition(arr, low, high)",
      "        quick_sort(arr, low, pi - 1)",
      "        quick_sort(arr, pi + 1, high)"
    ],
    java: [
      "public static void quickSort(int[] arr, int low, int high) {",
      "    if (low < high) {",
      "        int pi = partition(arr, low, high);",
      "        quickSort(arr, low, pi - 1);",
      "        quickSort(arr, pi + 1, high);",
      "    }",
      "}"
    ],
    cpp: [
      "void quickSort(int arr[], int low, int high) {",
      "    if (low < high) {",
      "        int pi = partition(arr, low, high);",
      "        quickSort(arr, low, pi - 1);",
      "        quickSort(arr, pi + 1, high);",
      "    }",
      "}"
    ],
    c: [
      "void quickSort(int arr[], int low, int high) {",
      "    if (low < high) {",
      "        int pi = partition(arr, low, high);",
      "        quickSort(arr, low, pi - 1);",
      "        quickSort(arr, pi + 1, high);",
      "    }",
      "}"
    ],
    typescript: [
      "function quickSort(arr: number[], low: number = 0, high: number = arr.length - 1): number[] {",
      "  if (low < high) {",
      "    let pi = partition(arr, low, high);",
      "    quickSort(arr, low, pi - 1);",
      "    quickSort(arr, pi + 1, high);",
      "  }",
      "  return arr;",
      "}"
    ],
    go: [
      "func quickSort(arr []int, low, high int) {",
      "    if low < high {",
      "        pi := partition(arr, low, high)",
      "        quickSort(arr, low, pi-1)",
      "        quickSort(arr, pi+1, high)",
      "    }",
      "}"
    ],
    php: [
      "function quickSort(array &$arr, int $low, int $high): void {",
      "    if ($low < $high) {",
      "        $pi = partition($arr, $low, $high);",
      "        quickSort($arr, $low, $pi - 1);",
      "        quickSort($arr, $pi + 1, $high);",
      "    }",
      "}"
    ],
    rust: [
      "fn quick_sort(arr: &mut [i32]) {",
      "    let len = arr.len();",
      "    if len <= 1 {",
      "        return;",
      "    }",
      "    let pivot = partition(arr);",
      "    quick_sort(&mut arr[..pivot]);",
      "    quick_sort(&mut arr[pivot + 1..]);",
      "}"
    ]
  },
  heapSort: {
    pseudocode: [
      "function heapSort(arr):",
      "  buildMaxHeap(arr)",
      "  for i from n-1 to 1:",
      "    swap(arr[0], arr[i])",
      "    heapify(arr, 0, i)"
    ],
    javascript: [
      "function heapSort(arr) {",
      "  let n = arr.length;",
      "  for (let i = Math.floor(n / 2) - 1; i >= 0; i--) heapify(arr, n, i);",
      "  for (let i = n - 1; i > 0; i--) {",
      "    [arr[0], arr[i]] = [arr[i], arr[0]];",
      "    heapify(arr, i, 0);",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def heap_sort(arr):",
      "    n = len(arr)",
      "    for i in range(n // 2 - 1, -1, -1): heapify(arr, n, i)",
      "    for i in range(n - 1, 0, -1):",
      "        arr[0], arr[i] = arr[i], arr[0]",
      "        heapify(arr, i, 0)",
      "    return arr"
    ],
    java: [
      "public static void heapSort(int[] arr) {",
      "    int n = arr.length;",
      "    for (int i = n / 2 - 1; i >= 0; i--) heapify(arr, n, i);",
      "    for (int i = n - 1; i > 0; i--) {",
      "        int temp = arr[0]; arr[0] = arr[i]; arr[i] = temp;",
      "        heapify(arr, i, 0);",
      "    }",
      "}"
    ],
    cpp: [
      "void heapSort(int arr[], int n) {",
      "    for (int i = n / 2 - 1; i >= 0; i--) heapify(arr, n, i);",
      "    for (int i = n - 1; i > 0; i--) {",
      "        std::swap(arr[0], arr[i]);",
      "        heapify(arr, i, 0);",
      "    }",
      "}"
    ],
    c: [
      "void heapSort(int arr[], int n) {",
      "    for (int i = n / 2 - 1; i >= 0; i--) heapify(arr, n, i);",
      "    for (int i = n - 1; i > 0; i--) {",
      "        int temp = arr[0]; arr[0] = arr[i]; arr[i] = temp;",
      "        heapify(arr, i, 0);",
      "    }",
      "}"
    ],
    typescript: [
      "function heapSort(arr: number[]): number[] {",
      "  let n = arr.length;",
      "  for (let i = Math.floor(n / 2) - 1; i >= 0; i--) heapify(arr, n, i);",
      "  for (let i = n - 1; i > 0; i--) {",
      "    [arr[0], arr[i]] = [arr[i], arr[0]];",
      "    heapify(arr, i, 0);",
      "  }",
      "  return arr;",
      "}"
    ],
    go: [
      "func heapSort(arr []int) {",
      "    n := len(arr)",
      "    for i := n/2 - 1; i >= 0; i-- {",
      "        heapify(arr, n, i)",
      "    }",
      "    for i := n - 1; i > 0; i-- {",
      "        arr[0], arr[i] = arr[i], arr[0]",
      "        heapify(arr, i, 0)",
      "    }",
      "}"
    ],
    php: [
      "function heapSort(array &$arr): void {",
      "    $n = count($arr);",
      "    for ($i = floor($n / 2) - 1; $i >= 0; $i--) {",
      "        heapify($arr, $n, $i);",
      "    }",
      "    for ($i = $n - 1; $i > 0; $i--) {",
      "        $temp = $arr[0];",
      "        $arr[0] = $arr[$i];",
      "        $arr[$i] = $temp;",
      "        heapify($arr, $i, 0);",
      "    }",
      "}"
    ],
    rust: [
      "fn heap_sort(arr: &mut [i32]) {",
      "    let len = arr.len();",
      "    for i in (0..len / 2).rev() {",
      "        heapify(arr, len, i);",
      "    }",
      "    for i in (1..len).rev() {",
      "        arr.swap(0, i);",
      "        heapify(arr, i, 0);",
      "    }",
      "}"
    ]
  },
  shellSort: {
    pseudocode: [
      "gap = n / 2",
      "while gap > 0:",
      "  for i from gap to n:",
      "    temp = arr[i]",
      "    j = i",
      "    while j >= gap and arr[j-gap] > temp:",
      "      arr[j] = arr[j-gap]",
      "    arr[j] = temp",
      "  gap = gap / 2"
    ],
    javascript: [
      "function shellSort(arr) {",
      "  let n = arr.length;",
      "  for (let gap = Math.floor(n / 2); gap > 0; gap = Math.floor(gap / 2)) {",
      "    for (let i = gap; i < n; i++) {",
      "      let temp = arr[i];",
      "      let j;",
      "      for (j = i; j >= gap && arr[j - gap] > temp; j -= gap) {",
      "        arr[j] = arr[j - gap];",
      "      }",
      "      arr[j] = temp;",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def shell_sort(arr):",
      "    n = len(arr)",
      "    gap = n // 2",
      "    while gap > 0:",
      "        for i in range(gap, n):",
      "            temp = arr[i]",
      "            j = i",
      "            while j >= gap and arr[j - gap] > temp:",
      "                arr[j] = arr[j - gap]",
      "                j -= gap",
      "            arr[j] = temp",
      "        gap //= 2",
      "    return arr"
    ],
    java: [
      "public static void shellSort(int[] arr) {",
      "    int n = arr.length;",
      "    for (int gap = n / 2; gap > 0; gap /= 2) {",
      "        for (int i = gap; i < n; i++) {",
      "            int temp = arr[i];",
      "            int j;",
      "            for (j = i; j >= gap && arr[j - gap] > temp; j -= gap) {",
      "                arr[j] = arr[j - gap];",
      "            }",
      "            arr[j] = temp;",
      "        }",
      "    }",
      "}"
    ],
    cpp: [
      "void shellSort(int arr[], int n) {",
      "    for (int gap = n / 2; gap > 0; gap /= 2) {",
      "        for (int i = gap; i < n; i++) {",
      "            int temp = arr[i];",
      "            int j;",
      "            for (j = i; j >= gap && arr[j - gap] > temp; j -= gap) {",
      "                arr[j] = arr[j - gap];",
      "            }",
      "            arr[j] = temp;",
      "        }",
      "    }",
      "}"
    ],
    c: [
      "void shellSort(int arr[], int n) {",
      "    for (int gap = n / 2; gap > 0; gap /= 2) {",
      "        for (int i = gap; i < n; i++) {",
      "            int temp = arr[i];",
      "            int j;",
      "            for (j = i; j >= gap && arr[j - gap] > temp; j -= gap) {",
      "                arr[j] = arr[j - gap];",
      "            }",
      "            arr[j] = temp;",
      "        }",
      "    }",
      "}"
    ],
    typescript: [
      "function shellSort(arr: number[]): number[] {",
      "  let n = arr.length;",
      "  for (let gap = Math.floor(n / 2); gap > 0; gap = Math.floor(gap / 2)) {",
      "    for (let i = gap; i < n; i++) {",
      "      let temp = arr[i];",
      "      let j;",
      "      for (j = i; j >= gap && arr[j - gap] > temp; j -= gap) {",
      "        arr[j] = arr[j - gap];",
      "      }",
      "      arr[j] = temp;",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    go: [
      "func shellSort(arr []int) {",
      "    n := len(arr)",
      "    for gap := n / 2; gap > 0; gap /= 2 {",
      "        for i := gap; i < n; i++ {",
      "            temp := arr[i]",
      "            j := i",
      "            for ; j >= gap && arr[j-gap] > temp; j -= gap {",
      "                arr[j] = arr[j-gap]",
      "            }",
      "            arr[j] = temp",
      "        }",
      "    }",
      "}"
    ],
    php: [
      "function shellSort(array &$arr): void {",
      "    $n = count($arr);",
      "    for ($gap = floor($n / 2); $gap > 0; $gap = floor($gap / 2)) {",
      "        for ($i = $gap; $i < $n; $i++) {",
      "            $temp = $arr[$i];",
      "            $j = $i;",
      "            for (; $j >= $gap && $arr[$j - $gap] > $temp; $j -= $gap) {",
      "                $arr[$j] = $arr[$j - $gap];",
      "            }",
      "            $arr[$j] = $temp;",
      "        }",
      "    }",
      "}"
    ],
    rust: [
      "fn shell_sort(arr: &mut [i32]) {",
      "    let len = arr.len();",
      "    let mut gap = len / 2;",
      "    while gap > 0 {",
      "        for i in gap..len {",
      "            let temp = arr[i];",
      "            let mut j = i;",
      "            while j >= gap && arr[j - gap] > temp {",
      "                arr[j] = arr[j - gap];",
      "                j -= gap;",
      "            }",
      "            arr[j] = temp;",
      "        }",
      "        gap /= 2;",
      "    }",
      "}"
    ]
  },
  cocktailSort: {
    pseudocode: [
      "do:",
      "  swapped = false",
      "  for i from 0 to n-1:",
      "    if arr[i] > arr[i+1]: swap and set swapped",
      "  for i from n-1 to 0:",
      "    if arr[i] > arr[i+1]: swap and set swapped",
      "while swapped"
    ],
    javascript: [
      "function cocktailSort(arr) {",
      "  let swapped = true;",
      "  let start = 0, end = arr.length - 1;",
      "  while (swapped) {",
      "    swapped = false;",
      "    for (let i = start; i < end; i++) {",
      "      if (arr[i] > arr[i + 1]) {",
      "        [arr[i], arr[i + 1]] = [arr[i + 1], arr[i]];",
      "        swapped = true;",
      "      }",
      "    }",
      "    if (!swapped) break;",
      "    swapped = false;",
      "    end--;",
      "    for (let i = end - 1; i >= start; i--) {",
      "      if (arr[i] > arr[i + 1]) {",
      "        [arr[i], arr[i + 1]] = [arr[i + 1], arr[i]];",
      "        swapped = true;",
      "      }",
      "    }",
      "    start++;",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def cocktail_sort(arr):",
      "    n = len(arr)",
      "    swapped = True",
      "    start, end = 0, n - 1",
      "    while swapped:",
      "        swapped = False",
      "        for i in range(start, end):",
      "            if arr[i] > arr[i + 1]:",
      "                arr[i], arr[i + 1] = arr[i + 1], arr[i]",
      "                swapped = True",
      "        if not swapped: break",
      "        swapped = False",
      "        end -= 1",
      "        for i in range(end - 1, start - 1, -1):",
      "            if arr[i] > arr[i + 1]:",
      "                arr[i], arr[i + 1] = arr[i + 1], arr[i]",
      "                swapped = True",
      "        start += 1",
      "    return arr"
    ],
    java: [
      "public static void cocktailSort(int[] arr) {",
      "    boolean swapped = true;",
      "    int start = 0, end = arr.length - 1;",
      "    while (swapped) {",
      "        swapped = false;",
      "        for (int i = start; i < end; i++) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                swapped = true;",
      "            }",
      "        }",
      "        if (!swapped) break;",
      "        swapped = false;",
      "        end--;",
      "        for (int i = end - 1; i >= start; i--) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                swapped = true;",
      "            }",
      "        }",
      "        start++;",
      "    }",
      "}"
    ],
    cpp: [
      "void cocktailSort(int arr[], int n) {",
      "    bool swapped = true;",
      "    int start = 0, end = n - 1;",
      "    while (swapped) {",
      "        swapped = false;",
      "        for (int i = start; i < end; ++i) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                std::swap(arr[i], arr[i + 1]);",
      "                swapped = true;",
      "            }",
      "        }",
      "        if (!swapped) break;",
      "        swapped = false;",
      "        --end;",
      "        for (int i = end - 1; i >= start; --i) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                std::swap(arr[i], arr[i + 1]);",
      "                swapped = true;",
      "            }",
      "        }",
      "        ++start;",
      "    }",
      "}"
    ],
    c: [
      "void cocktailSort(int arr[], int n) {",
      "    int swapped = 1;",
      "    int start = 0, end = n - 1;",
      "    while (swapped) {",
      "        swapped = 0;",
      "        for (int i = start; i < end; ++i) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                swapped = 1;",
      "            }",
      "        }",
      "        if (!swapped) break;",
      "        swapped = 0;",
      "        --end;",
      "        for (int i = end - 1; i >= start; --i) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                swapped = 1;",
      "            }",
      "        }",
      "        ++start;",
      "    }",
      "}"
    ],
    typescript: [
      "function cocktailSort(arr: number[]): number[] {",
      "  let swapped = true;",
      "  let start = 0, end = arr.length - 1;",
      "  while (swapped) {",
      "    swapped = false;",
      "    for (let i = start; i < end; i++) {",
      "      if (arr[i] > arr[i + 1]) {",
      "        [arr[i], arr[i + 1]] = [arr[i + 1], arr[i]];",
      "        swapped = true;",
      "      }",
      "    }",
      "    if (!swapped) break;",
      "    swapped = false;",
      "    end--;",
      "    for (let i = end - 1; i >= start; i--) {",
      "      if (arr[i] > arr[i + 1]) {",
      "        [arr[i], arr[i + 1]] = [arr[i + 1], arr[i]];",
      "        swapped = true;",
      "      }",
      "    }",
      "    start++;",
      "  }",
      "  return arr;",
      "}"
    ],
    go: [
      "func cocktailSort(arr []int) {",
      "    swapped := true",
      "    start := 0",
      "    end := len(arr) - 1",
      "    for swapped {",
      "        swapped = false",
      "        for i := start; i < end; i++ {",
      "            if arr[i] > arr[i+1] {",
      "                arr[i], arr[i+1] = arr[i+1], arr[i]",
      "                swapped = true",
      "            }",
      "        }",
      "        if !swapped {",
      "            break",
      "        }",
      "        swapped = false",
      "        end--",
      "        for i := end - 1; i >= start; i-- {",
      "            if arr[i] > arr[i+1] {",
      "                arr[i], arr[i+1] = arr[i+1], arr[i]",
      "                swapped = true",
      "            }",
      "        }",
      "        start++",
      "    }",
      "}"
    ],
    php: [
      "function cocktailSort(array &$arr): void {",
      "    $swapped = true;",
      "    $start = 0;",
      "    $end = count($arr) - 1;",
      "    while ($swapped) {",
      "        $swapped = false;",
      "        for ($i = $start; $i < $end; $i++) {",
      "            if ($arr[$i] > $arr[$i + 1]) {",
      "                $temp = $arr[$i]; $arr[$i] = $arr[$i + 1]; $arr[$i + 1] = $temp;",
      "                $swapped = true;",
      "            }",
      "        }",
      "        if (!$swapped) break;",
      "        $swapped = false;",
      "        $end--;",
      "        for ($i = $end - 1; $i >= $start; $i--) {",
      "            if ($arr[$i] > $arr[$i + 1]) {",
      "                $temp = $arr[$i]; $arr[$i] = $arr[$i + 1]; $arr[$i + 1] = $temp;",
      "                $swapped = true;",
      "            }",
      "        }",
      "        $start++;",
      "    }",
      "}"
    ],
    rust: [
      "fn cocktail_sort(arr: &mut [i32]) {",
      "    let mut swapped = true;",
      "    let mut start = 0;",
      "    let mut end = arr.len().saturating_sub(1);",
      "    while swapped {",
      "        swapped = false;",
      "        for i in start..end {",
      "            if arr[i] > arr[i + 1] {",
      "                arr.swap(i, i + 1);",
      "                swapped = true;",
      "            }",
      "        }",
      "        if !swapped { break; }",
      "        swapped = false;",
      "        end -= 1;",
      "        for i in (start..end).rev() {",
      "            if arr[i] > arr[i + 1] {",
      "                arr.swap(i, i + 1);",
      "                swapped = true;",
      "            }",
      "        }",
      "        start += 1;",
      "    }",
      "}"
    ]
  },
  combSort: {
    pseudocode: [
      "gap = n",
      "shrink = 1.3",
      "while gap > 1:",
      "  gap = floor(gap / shrink)",
      "  for i from 0 to n-gap:",
      "    if arr[i] > arr[i+gap]:",
      "      swap(arr[i], arr[i+gap])"
    ],
    javascript: [
      "function combSort(arr) {",
      "  let n = arr.length;",
      "  let gap = n;",
      "  let shrink = 1.3;",
      "  let sorted = false;",
      "  while (gap > 1 || !sorted) {",
      "    gap = Math.floor(gap / shrink);",
      "    if (gap < 1) gap = 1;",
      "    sorted = true;",
      "    for (let i = 0; i + gap < n; i++) {",
      "      if (arr[i] > arr[i + gap]) {",
      "        [arr[i], arr[i + gap]] = [arr[i + gap], arr[i]];",
      "        sorted = false;",
      "      }",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def comb_sort(arr):",
      "    n = len(arr)",
      "    gap = n",
      "    shrink = 1.3",
      "    sorted = False",
      "    while gap > 1 or not sorted:",
      "        gap = int(gap / shrink)",
      "        if gap < 1: gap = 1",
      "        sorted = True",
      "        for i in range(0, n - gap):",
      "            if arr[i] > arr[i + gap]:",
      "                arr[i], arr[i + gap] = arr[i + gap], arr[i]",
      "                sorted = False",
      "    return arr"
    ],
    java: [
      "public static void combSort(int[] arr) {",
      "    int n = arr.length;",
      "    int gap = n;",
      "    float shrink = 1.3f;",
      "    boolean swapped = true;",
      "    while (gap > 1 || swapped) {",
      "        gap = (int)(gap / shrink);",
      "        if (gap < 1) gap = 1;",
      "        swapped = false;",
      "        for (int i = 0; i + gap < n; i++) {",
      "            if (arr[i] > arr[i + gap]) {",
      "                int temp = arr[i]; arr[i] = arr[i + gap]; arr[i + gap] = temp;",
      "                swapped = true;",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    cpp: [
      "void combSort(int arr[], int n) {",
      "    int gap = n;",
      "    float shrink = 1.3;",
      "    bool swapped = true;",
      "    while (gap > 1 || swapped) {",
      "        gap = gap / shrink;",
      "        if (gap < 1) gap = 1;",
      "        swapped = false;",
      "        for (int i = 0; i + gap < n; i++) {",
      "            if (arr[i] > arr[i + gap]) {",
      "                std::swap(arr[i], arr[i + gap]);",
      "                swapped = true;",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    c: [
      "void combSort(int arr[], int n) {",
      "    int gap = n;",
      "    float shrink = 1.3;",
      "    int swapped = 1;",
      "    while (gap > 1 || swapped) {",
      "        gap = gap / shrink;",
      "        if (gap < 1) gap = 1;",
      "        swapped = 0;",
      "        for (int i = 0; i + gap < n; i++) {",
      "            if (arr[i] > arr[i + gap]) {",
      "                int temp = arr[i]; arr[i] = arr[i + gap]; arr[i + gap] = temp;",
      "                swapped = 1;",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    typescript: [
      "function combSort(arr: number[]): number[] {",
      "  let n = arr.length;",
      "  let gap = n;",
      "  let shrink = 1.3;",
      "  let sorted = false;",
      "  while (gap > 1 || !sorted) {",
      "    gap = Math.floor(gap / shrink);",
      "    if (gap < 1) gap = 1;",
      "    sorted = true;",
      "    for (let i = 0; i + gap < n; i++) {",
      "      if (arr[i] > arr[i + gap]) {",
      "        [arr[i], arr[i + gap]] = [arr[i + gap], arr[i]];",
      "        sorted = false;",
      "      }",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    go: [
      "func combSort(arr []int) {",
      "    n := len(arr)",
      "    gap := n",
      "    shrink := 1.3",
      "    sorted := false",
      "    for gap > 1 || !sorted {",
      "        gap = int(float64(gap) / shrink)",
      "        if gap < 1 {",
      "            gap = 1",
      "        }",
      "        sorted = true",
      "        for i := 0; i+gap < n; i++ {",
      "            if arr[i] > arr[i+gap] {",
      "                arr[i], arr[i+gap] = arr[i+gap], arr[i]",
      "                sorted = false",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    php: [
      "function combSort(array &$arr): void {",
      "    $n = count($arr);",
      "    $gap = $n;",
      "    $shrink = 1.3;",
      "    $sorted = false;",
      "    while ($gap > 1 || !$sorted) {",
      "        $gap = floor($gap / $shrink);",
      "        if ($gap < 1) $gap = 1;",
      "        $sorted = true;",
      "        for ($i = 0; $i + $gap < $n; $i++) {",
      "            if ($arr[$i] > $arr[$i + $gap]) {",
      "                $temp = $arr[$i]; $arr[$i] = $arr[$i + $gap]; $arr[$i + $gap] = $temp;",
      "                $sorted = false;",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    rust: [
      "fn comb_sort(arr: &mut [i32]) {",
      "    let len = arr.len();",
      "    let mut gap = len;",
      "    let mut sorted = false;",
      "    while gap > 1 || !sorted {",
      "        gap = (gap as f64 / 1.3) as usize;",
      "        if gap < 1 { gap = 1; }",
      "        sorted = true;",
      "        for i in 0..len - gap {",
      "            if arr[i] > arr[i + gap] {",
      "                arr.swap(i, i + gap);",
      "                sorted = false;",
      "            }",
      "        }",
      "    }",
      "}"
    ]
  },
  gnomeSort: {
    pseudocode: [
      "pos = 0",
      "while pos < n:",
      "  if pos == 0 or arr[pos] >= arr[pos-1]:",
      "    pos = pos + 1",
      "  else:",
      "    swap(arr[pos], arr[pos-1])",
      "    pos = pos - 1"
    ],
    javascript: [
      "function gnomeSort(arr) {",
      "  let n = arr.length;",
      "  let index = 0;",
      "  while (index < n) {",
      "    if (index === 0 || arr[index] >= arr[index - 1]) {",
      "      index++;",
      "    } else {",
      "      [arr[index], arr[index - 1]] = [arr[index - 1], arr[index]];",
      "      index--;",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def gnome_sort(arr):",
      "    n = len(arr)",
      "    index = 0",
      "    while index < n:",
      "        if index == 0 or arr[index] >= arr[index - 1]:",
      "            index += 1",
      "        else:",
      "            arr[index], arr[index - 1] = arr[index - 1], arr[index]",
      "            index -= 1",
      "    return arr"
    ],
    java: [
      "public static void gnomeSort(int[] arr) {",
      "    int n = arr.length;",
      "    int index = 0;",
      "    while (index < n) {",
      "        if (index == 0 || arr[index] >= arr[index - 1]) {",
      "            index++;",
      "        } else {",
      "            int temp = arr[index]; arr[index] = arr[index - 1]; arr[index - 1] = temp;",
      "            index--;",
      "        }",
      "    }",
      "}"
    ],
    cpp: [
      "void gnomeSort(int arr[], int n) {",
      "    int index = 0;",
      "    while (index < n) {",
      "        if (index == 0 || arr[index] >= arr[index - 1]) {",
      "            index++;",
      "        } else {",
      "            std::swap(arr[index], arr[index - 1]);",
      "            index--;",
      "        }",
      "    }",
      "}"
    ],
    c: [
      "void gnomeSort(int arr[], int n) {",
      "    int index = 0;",
      "    while (index < n) {",
      "        if (index == 0 || arr[index] >= arr[index - 1]) {",
      "            index++;",
      "        } else {",
      "            int temp = arr[index]; arr[index] = arr[index - 1]; arr[index - 1] = temp;",
      "            index--;",
      "        }",
      "    }",
      "}"
    ],
    typescript: [
      "function gnomeSort(arr: number[]): number[] {",
      "  let n = arr.length;",
      "  let index = 0;",
      "  while (index < n) {",
      "    if (index === 0 || arr[index] >= arr[index - 1]) {",
      "      index++;",
      "    } else {",
      "      [arr[index], arr[index - 1]] = [arr[index - 1], arr[index]];",
      "      index--;",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    go: [
      "func gnomeSort(arr []int) {",
      "    n := len(arr)",
      "    index := 0",
      "    for index < n {",
      "        if index == 0 || arr[index] >= arr[index-1] {",
      "            index++",
      "        } else {",
      "            arr[index], arr[index-1] = arr[index-1], arr[index]",
      "            index--",
      "        }",
      "    }",
      "}"
    ],
    php: [
      "function gnomeSort(array &$arr): void {",
      "    $n = count($arr);",
      "    $index = 0;",
      "    while ($index < $n) {",
      "        if ($index == 0 || $arr[$index] >= $arr[$index - 1]) {",
      "            $index++;",
      "        } else {",
      "            $temp = $arr[$index]; $arr[$index] = $arr[$index - 1]; $arr[$index - 1] = $temp;",
      "            $index--;",
      "        }",
      "    }",
      "}"
    ],
    rust: [
      "fn gnome_sort(arr: &mut [i32]) {",
      "    let len = arr.len();",
      "    let mut index = 0;",
      "    while index < len {",
      "        if index == 0 || arr[index] >= arr[index - 1] {",
      "            index += 1;",
      "        } else {",
      "            arr.swap(index, index - 1);",
      "            index -= 1;",
      "        }",
      "    }",
      "}"
    ]
  },
  oddEvenSort: {
    pseudocode: [
      "sorted = false",
      "while not sorted:",
      "  sorted = true",
      "  for i in odd indices:",
      "    if arr[i] > arr[i+1]: swap and mark unsorted",
      "  for i in even indices:",
      "    if arr[i] > arr[i+1]: swap and mark unsorted"
    ],
    javascript: [
      "function oddEvenSort(arr) {",
      "  let n = arr.length;",
      "  let sorted = false;",
      "  while (!sorted) {",
      "    sorted = true;",
      "    for (let i = 1; i < n - 1; i += 2) {",
      "      if (arr[i] > arr[i + 1]) {",
      "        [arr[i], arr[i + 1]] = [arr[i + 1], arr[i]];",
      "        sorted = false;",
      "      }",
      "    }",
      "    for (let i = 0; i < n - 1; i += 2) {",
      "      if (arr[i] > arr[i + 1]) {",
      "        [arr[i], arr[i + 1]] = [arr[i + 1], arr[i]];",
      "        sorted = false;",
      "      }",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def odd_even_sort(arr):",
      "    n = len(arr)",
      "    sorted = False",
      "    while not sorted:",
      "        sorted = True",
      "        for i in range(1, n - 1, 2):",
      "            if arr[i] > arr[i + 1]:",
      "                arr[i], arr[i + 1] = arr[i + 1], arr[i]",
      "                sorted = False",
      "        for i in range(0, n - 1, 2):",
      "            if arr[i] > arr[i + 1]:",
      "                arr[i], arr[i + 1] = arr[i + 1], arr[i]",
      "                sorted = False",
      "    return arr"
    ],
    java: [
      "public static void oddEvenSort(int[] arr) {",
      "    int n = arr.length;",
      "    boolean sorted = false;",
      "    while (!sorted) {",
      "        sorted = true;",
      "        for (int i = 1; i < n - 1; i += 2) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                sorted = false;",
      "            }",
      "        }",
      "        for (int i = 0; i < n - 1; i += 2) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                sorted = false;",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    cpp: [
      "void oddEvenSort(int arr[], int n) {",
      "    bool sorted = false;",
      "    while (!sorted) {",
      "        sorted = true;",
      "        for (int i = 1; i < n - 1; i += 2) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                std::swap(arr[i], arr[i + 1]);",
      "                sorted = false;",
      "            }",
      "        }",
      "        for (int i = 0; i < n - 1; i += 2) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                std::swap(arr[i], arr[i + 1]);",
      "                sorted = false;",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    c: [
      "void oddEvenSort(int arr[], int n) {",
      "    int sorted = 0;",
      "    while (!sorted) {",
      "        sorted = 1;",
      "        for (int i = 1; i < n - 1; i += 2) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                sorted = 0;",
      "            }",
      "        }",
      "        for (int i = 0; i < n - 1; i += 2) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                sorted = 0;",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    typescript: [
      "function oddEvenSort(arr: number[]): number[] {",
      "  let n = arr.length;",
      "  let sorted = false;",
      "  while (!sorted) {",
      "    sorted = true;",
      "    for (let i = 1; i < n - 1; i += 2) {",
      "      if (arr[i] > arr[i + 1]) {",
      "        [arr[i], arr[i + 1]] = [arr[i + 1], arr[i]];",
      "        sorted = false;",
      "      }",
      "    }",
      "    for (let i = 0; i < n - 1; i += 2) {",
      "      if (arr[i] > arr[i + 1]) {",
      "        [arr[i], arr[i + 1]] = [arr[i + 1], arr[i]];",
      "        sorted = false;",
      "      }",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    go: [
      "func oddEvenSort(arr []int) {",
      "    n := len(arr)",
      "    sorted := false",
      "    for !sorted {",
      "        sorted = true",
      "        for i := 1; i < n-1; i += 2 {",
      "            if arr[i] > arr[i+1] {",
      "                arr[i], arr[i+1] = arr[i+1], arr[i]",
      "                sorted = false",
      "            }",
      "        }",
      "        for i := 0; i < n-1; i += 2 {",
      "            if arr[i] > arr[i+1] {",
      "                arr[i], arr[i+1] = arr[i+1], arr[i]",
      "                sorted = false",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    php: [
      "function oddEvenSort(array &$arr): void {",
      "    $n = count($arr);",
      "    $sorted = false;",
      "    while (!$sorted) {",
      "        $sorted = true;",
      "        for ($i = 1; $i < $n - 1; $i += 2) {",
      "            if ($arr[$i] > $arr[$i + 1]) {",
      "                $temp = $arr[$i]; $arr[$i] = $arr[$i + 1]; $arr[$i + 1] = $temp;",
      "                $sorted = false;",
      "            }",
      "        }",
      "        for ($i = 0; $i < $n - 1; $i += 2) {",
      "            if ($arr[$i] > $arr[$i + 1]) {",
      "                $temp = $arr[$i]; $arr[$i] = $arr[$i + 1]; $arr[$i + 1] = $temp;",
      "                $sorted = false;",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    rust: [
      "fn odd_even_sort(arr: &mut [i32]) {",
      "    let len = arr.len();",
      "    if len < 2 { return; }",
      "    let mut sorted = false;",
      "    while !sorted {",
      "        sorted = true;",
      "        let mut i = 1;",
      "        while i < len - 1 {",
      "            if arr[i] > arr[i + 1] {",
      "                arr.swap(i, i + 1);",
      "                sorted = false;",
      "            }",
      "            i += 2;",
      "        }",
      "        let mut i = 0;",
      "        while i < len - 1 {",
      "            if arr[i] > arr[i + 1] {",
      "                arr.swap(i, i + 1);",
      "                sorted = false;",
      "            }",
      "            i += 2;",
      "        }",
      "    }",
      "}"
    ]
  },
  pancakeSort: {
    pseudocode: [
      "for curr_size from n to 1:",
      "  max_idx = findMax(arr, curr_size)",
      "  if max_idx != curr_size-1:",
      "    flip(arr, max_idx)",
      "    flip(arr, curr_size-1)"
    ],
    javascript: [
      "function pancakeSort(arr) {",
      "  let n = arr.length;",
      "  for (let currSize = n; currSize > 1; currSize--) {",
      "    let maxIdx = findMax(arr, currSize);",
      "    if (maxIdx !== currSize - 1) {",
      "      flip(arr, maxIdx);",
      "      flip(arr, currSize - 1);",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def pancake_sort(arr):",
      "    n = len(arr)",
      "    for curr_size in range(n, 1, -1):",
      "        max_idx = arr.index(max(arr[:curr_size]))",
      "        if max_idx != curr_size - 1:",
      "            arr[:max_idx + 1] = reversed(arr[:max_idx + 1])",
      "            arr[:curr_size] = reversed(arr[:curr_size])",
      "    return arr"
    ],
    java: [
      "public static void pancakeSort(int[] arr) {",
      "    int n = arr.length;",
      "    for (int currSize = n; currSize > 1; currSize--) {",
      "        int maxIdx = findMax(arr, currSize);",
      "        if (maxIdx != currSize - 1) {",
      "            flip(arr, maxIdx);",
      "            flip(arr, currSize - 1);",
      "        }",
      "    }",
      "}"
    ],
    cpp: [
      "void pancakeSort(int arr[], int n) {",
      "    for (int currSize = n; currSize > 1; --currSize) {",
      "        int maxIdx = findMax(arr, currSize);",
      "        if (maxIdx != currSize - 1) {",
      "            flip(arr, maxIdx);",
      "            flip(arr, currSize - 1);",
      "        }",
      "    }",
      "}"
    ],
    c: [
      "void pancakeSort(int arr[], int n) {",
      "    for (int currSize = n; currSize > 1; --currSize) {",
      "        int maxIdx = findMax(arr, currSize);",
      "        if (maxIdx != currSize - 1) {",
      "            flip(arr, maxIdx);",
      "            flip(arr, currSize - 1);",
      "        }",
      "    }",
      "}"
    ],
    typescript: [
      "function pancakeSort(arr: number[]): number[] {",
      "  let n = arr.length;",
      "  for (let currSize = n; currSize > 1; currSize--) {",
      "    let maxIdx = findMax(arr, currSize);",
      "    if (maxIdx !== currSize - 1) {",
      "      flip(arr, maxIdx);",
      "      flip(arr, currSize - 1);",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    go: [
      "func pancakeSort(arr []int) {",
      "    n := len(arr)",
      "    for currSize := n; currSize > 1; currSize-- {",
      "        maxIdx := findMax(arr, currSize)",
      "        if maxIdx != currSize-1 {",
      "            flip(arr, maxIdx)",
      "            flip(arr, currSize-1)",
      "        }",
      "    }",
      "}"
    ],
    php: [
      "function pancakeSort(array &$arr): void {",
      "    $n = count($arr);",
      "    for ($currSize = $n; $currSize > 1; $currSize--) {",
      "        $maxIdx = findMax($arr, $currSize);",
      "        if ($maxIdx != $currSize - 1) {",
      "            flip($arr, $maxIdx);",
      "            flip($arr, $currSize - 1);",
      "        }",
      "    }",
      "}"
    ],
    rust: [
      "fn pancake_sort(arr: &mut [i32]) {",
      "    let len = arr.len();",
      "    for curr_size in (2..=len).rev() {",
      "        let max_idx = find_max(&arr[..curr_size]);",
      "        if max_idx != curr_size - 1 {",
      "            arr[..=max_idx].reverse();",
      "            arr[..curr_size].reverse();",
      "        }",
      "    }",
      "}"
    ]
  },
  bitonicSortWrapper: {
    pseudocode: [
      "function bitonicSort(arr, up):",
      "  if length(arr) > 1:",
      "    m = length(arr) / 2",
      "    bitonicSort(arr[0:m], 1)",
      "    bitonicSort(arr[m:], 0)",
      "    bitonicMerge(arr, up)"
    ],
    javascript: [
      "function bitonicSort(arr, low, cnt, dir) {",
      "  if (cnt > 1) {",
      "    let k = cnt / 2;",
      "    bitonicSort(arr, low, k, 1);",
      "    bitonicSort(arr, low + k, k, 0);",
      "    bitonicMerge(arr, low, cnt, dir);",
      "  }",
      "}"
    ],
    python: [
      "def bitonic_sort(arr, low, cnt, direction):",
      "    if cnt > 1:",
      "        k = cnt // 2",
      "        bitonic_sort(arr, low, k, 1)",
      "        bitonic_sort(arr, low + k, k, 0)",
      "        bitonic_merge(arr, low, cnt, direction)"
    ],
    java: [
      "public static void bitonicSort(int[] arr, int low, int cnt, int dir) {",
      "    if (cnt > 1) {",
      "        int k = cnt / 2;",
      "        bitonicSort(arr, low, k, 1);",
      "        bitonicSort(arr, low + k, k, 0);",
      "        bitonicMerge(arr, low, cnt, dir);",
      "    }",
      "}"
    ],
    cpp: [
      "void bitonicSort(int arr[], int low, int cnt, int dir) {",
      "    if (cnt > 1) {",
      "        int k = cnt / 2;",
      "        bitonicSort(arr, low, k, 1);",
      "        bitonicSort(arr, low + k, k, 0);",
      "        bitonicMerge(arr, low, cnt, dir);",
      "    }",
      "}"
    ],
    c: [
      "void bitonicSort(int arr[], int low, int cnt, int dir) {",
      "    if (cnt > 1) {",
      "        int k = cnt / 2;",
      "        bitonicSort(arr, low, k, 1);",
      "        bitonicSort(arr, low + k, k, 0);",
      "        bitonicMerge(arr, low, cnt, dir);",
      "    }",
      "}"
    ],
    typescript: [
      "function bitonicSort(arr: number[], low: number, cnt: number, dir: number): void {",
      "  if (cnt > 1) {",
      "    let k = Math.floor(cnt / 2);",
      "    bitonicSort(arr, low, k, 1);",
      "    bitonicSort(arr, low + k, k, 0);",
      "    bitonicMerge(arr, low, cnt, dir);",
      "  }",
      "}"
    ],
    go: [
      "func bitonicSort(arr []int, low, cnt, dir int) {",
      "    if cnt > 1 {",
      "        k := cnt / 2",
      "        bitonicSort(arr, low, k, 1)",
      "        bitonicSort(arr, low+k, k, 0)",
      "        bitonicMerge(arr, low, cnt, dir)",
      "    }",
      "}"
    ],
    php: [
      "function bitonicSort(array &$arr, int $low, int $cnt, int $dir): void {",
      "    if ($cnt > 1) {",
      "        $k = intdiv($cnt, 2);",
      "        bitonicSort($arr, $low, $k, 1);",
      "        bitonicSort($arr, $low + $k, $k, 0);",
      "        bitonicMerge($arr, $low, $cnt, $dir);",
      "    }",
      "}"
    ],
    rust: [
      "fn bitonic_sort(arr: &mut [i32], low: usize, cnt: usize, dir: i32) {",
      "    if cnt > 1 {",
      "        let k = cnt / 2;",
      "        bitonic_sort(arr, low, k, 1);",
      "        bitonic_sort(arr, low + k, k, 0);",
      "        bitonic_merge(arr, low, cnt, dir);",
      "    }",
      "}"
    ]
  },
  radixSort: {
    pseudocode: [
      "for digit from LSD to MSD:",
      "  create buckets[0-9]",
      "  for each number in arr:",
      "    place in bucket by digit",
      "  collect from buckets back to arr"
    ],
    javascript: [
      "function radixSort(arr) {",
      "  let max = Math.max(...arr);",
      "  for (let exp = 1; Math.floor(max / exp) > 0; exp *= 10) {",
      "    countingSortForRadix(arr, exp);",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def radix_sort(arr):",
      "    max_val = max(arr)",
      "    exp = 1",
      "    while max_val // exp > 0:",
      "        counting_sort_for_radix(arr, exp)",
      "        exp *= 10",
      "    return arr"
    ],
    java: [
      "public static void radixSort(int[] arr) {",
      "    int max = getMax(arr);",
      "    for (int exp = 1; max / exp > 0; exp *= 10) {",
      "        countingSort(arr, exp);",
      "    }",
      "}"
    ],
    cpp: [
      "void radixSort(int arr[], int n) {",
      "    int m = getMax(arr, n);",
      "    for (int exp = 1; m / exp > 0; exp *= 10) {",
      "        countingSort(arr, n, exp);",
      "    }",
      "}"
    ],
    c: [
      "void radixSort(int arr[], int n) {",
      "    int m = getMax(arr, n);",
      "    for (int exp = 1; m / exp > 0; exp *= 10) {",
      "        countingSort(arr, n, exp);",
      "    }",
      "}"
    ],
    typescript: [
      "function radixSort(arr: number[]): number[] {",
      "  let max = Math.max(...arr);",
      "  for (let exp = 1; Math.floor(max / exp) > 0; exp *= 10) {",
      "    countingSortForRadix(arr, exp);",
      "  }",
      "  return arr;",
      "}"
    ],
    go: [
      "func radixSort(arr []int) {",
      "    max := getMax(arr)",
      "    for exp := 1; max/exp > 0; exp *= 10 {",
      "        countingSortForRadix(arr, exp)",
      "    }",
      "}"
    ],
    php: [
      "function radixSort(array &$arr): void {",
      "    if (empty($arr)) return;",
      "    $max = max($arr);",
      "    for ($exp = 1; floor($max / $exp) > 0; $exp *= 10) {",
      "        countingSortForRadix($arr, $exp);",
      "    }",
      "}"
    ],
    rust: [
      "fn radix_sort(arr: &mut [i32]) {",
      "    let max = match arr.iter().max() {",
      "        Some(&m) => m,",
      "        None => return,",
      "    };",
      "    let mut exp = 1;",
      "    while max / exp > 0 {",
      "        counting_sort_for_radix(arr, exp);",
      "        exp *= 10;",
      "    }",
      "}"
    ]
  },
  stoogeSortWrapper: {
    pseudocode: [
      "function stoogeSort(arr, i, j):",
      "  if arr[i] > arr[j]: swap(arr[i], arr[j])",
      "  if j - i + 1 > 2:",
      "    t = (j - i + 1) / 3",
      "    stoogeSort(arr, i, j-t)",
      "    stoogeSort(arr, i+t, j)",
      "    stoogeSort(arr, i, j-t)"
    ],
    javascript: [
      "function stoogeSort(arr, i = 0, j = arr.length - 1) {",
      "  if (arr[i] > arr[j]) [arr[i], arr[j]] = [arr[j], arr[i]];",
      "  if (j - i + 1 > 2) {",
      "    let t = Math.floor((j - i + 1) / 3);",
      "    stoogeSort(arr, i, j - t);",
      "    stoogeSort(arr, i + t, j);",
      "    stoogeSort(arr, i, j - t);",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def stooge_sort(arr, i, j):",
      "    if arr[i] > arr[j]:",
      "        arr[i], arr[j] = arr[j], arr[i]",
      "    if j - i + 1 > 2:",
      "        t = (j - i + 1) // 3",
      "        stooge_sort(arr, i, j - t)",
      "        stooge_sort(arr, i + t, j)",
      "        stooge_sort(arr, i, j - t)"
    ],
    java: [
      "public static void stoogeSort(int[] arr, int i, int j) {",
      "    if (arr[i] > arr[j]) {",
      "        int temp = arr[i]; arr[i] = arr[j]; arr[j] = temp;",
      "    }",
      "    if (j - i + 1 > 2) {",
      "        int t = (j - i + 1) / 3;",
      "        stoogeSort(arr, i, j - t);",
      "        stoogeSort(arr, i + t, j);",
      "        stoogeSort(arr, i, j - t);",
      "    }",
      "}"
    ],
    cpp: [
      "void stoogeSort(int arr[], int i, int j) {",
      "    if (arr[i] > arr[j]) std::swap(arr[i], arr[j]);",
      "    if (j - i + 1 > 2) {",
      "        int t = (j - i + 1) / 3;",
      "        stoogeSort(arr, i, j - t);",
      "        stoogeSort(arr, i + t, j);",
      "        stoogeSort(arr, i, j - t);",
      "    }",
      "}"
    ],
    c: [
      "void stoogeSort(int arr[], int i, int j) {",
      "    if (arr[i] > arr[j]) {",
      "        int temp = arr[i]; arr[i] = arr[j]; arr[j] = temp;",
      "    }",
      "    if (j - i + 1 > 2) {",
      "        int t = (j - i + 1) / 3;",
      "        stoogeSort(arr, i, j - t);",
      "        stoogeSort(arr, i + t, j);",
      "        stoogeSort(arr, i, j - t);",
      "    }",
      "}"
    ],
    typescript: [
      "function stoogeSort(arr: number[], i: number = 0, j: number = arr.length - 1): number[] {",
      "  if (arr[i] > arr[j]) [arr[i], arr[j]] = [arr[j], arr[i]];",
      "  if (j - i + 1 > 2) {",
      "    let t = Math.floor((j - i + 1) / 3);",
      "    stoogeSort(arr, i, j - t);",
      "    stoogeSort(arr, i + t, j);",
      "    stoogeSort(arr, i, j - t);",
      "  }",
      "  return arr;",
      "}"
    ],
    go: [
      "func stoogeSort(arr []int, i, j int) {",
      "    if arr[i] > arr[j] {",
      "        arr[i], arr[j] = arr[j], arr[i]",
      "    }",
      "    if j-i+1 > 2 {",
      "        t := (j - i + 1) / 3",
      "        stoogeSort(arr, i, j-t)",
      "        stoogeSort(arr, i+t, j)",
      "        stoogeSort(arr, i, j-t)",
      "    }",
      "}"
    ],
    php: [
      "function stoogeSort(array &$arr, int $i, int $j): void {",
      "    if ($arr[$i] > $arr[$j]) {",
      "        $temp = $arr[$i]; $arr[$i] = $arr[$j]; $arr[$j] = $temp;",
      "    }",
      "    if ($j - $i + 1 > 2) {",
      "        $t = (int)(($j - $i + 1) / 3);",
      "        stoogeSort($arr, $i, $j - $t);",
      "        stoogeSort($arr, $i + $t, $j);",
      "        stoogeSort($arr, $i, $j - $t);",
      "    }",
      "}"
    ],
    rust: [
      "fn stooge_sort(arr: &mut [i32], i: usize, j: usize) {",
      "    if arr[i] > arr[j] {",
      "        arr.swap(i, j);",
      "    }",
      "    if j - i + 1 > 2 {",
      "        let t = (j - i + 1) / 3;",
      "        stooge_sort(arr, i, j - t);",
      "        stooge_sort(arr, i + t, j);",
      "        stooge_sort(arr, i, j - t);",
      "    }",
      "}"
    ]
  },
  bogoSort: {
    pseudocode: [
      "while not isSorted(arr):",
      "  shuffle(arr)"
    ],
    javascript: [
      "function bogoSort(arr) {",
      "  while (!isSorted(arr)) {",
      "    shuffle(arr);",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def bogo_sort(arr):",
      "    while not is_sorted(arr):",
      "        shuffle(arr)",
      "    return arr"
    ],
    java: [
      "public static void bogoSort(int[] arr) {",
      "    while (!isSorted(arr)) {",
      "        shuffle(arr);",
      "    }",
      "}"
    ],
    cpp: [
      "void bogoSort(int arr[], int n) {",
      "    while (!isSorted(arr, n)) {",
      "        shuffle(arr, n);",
      "    }",
      "}"
    ],
    c: [
      "void bogoSort(int arr[], int n) {",
      "    while (!isSorted(arr, n)) {",
      "        shuffle(arr, n);",
      "    }",
      "}"
    ],
    typescript: [
      "function bogoSort(arr: number[]): number[] {",
      "  while (!isSorted(arr)) {",
      "    shuffle(arr);",
      "  }",
      "  return arr;",
      "}"
    ],
    go: [
      "func bogoSort(arr []int) {",
      "    for !isSorted(arr) {",
      "        shuffle(arr)",
      "    }",
      "}"
    ],
    php: [
      "function bogoSort(array &$arr): void {",
      "    while (!isSorted($arr)) {",
      "        shuffleArray($arr);",
      "    }",
      "}"
    ],
    rust: [
      "fn bogo_sort(arr: &mut [i32]) {",
      "    while !is_sorted(arr) {",
      "        shuffle(arr);",
      "    }",
      "}"
    ]
  },
  timSort: {
    pseudocode: [
      "RUN = 32",
      "for i from 0 to n by RUN:",
      "  insertionSort(arr, i, min((i+31), (n-1)))",
      "for size from RUN to n by size*2:",
      "  for left from 0 to n by 2*size:",
      "    mid = left + size - 1",
      "    right = min((left + 2*size - 1), (n-1))",
      "    if mid < right:",
      "      merge(arr, left, mid, right)"
    ],
    javascript: [
      "const RUN = 32;",
      "function timSort(arr, n) {",
      "  for (let i = 0; i < n; i += RUN) {",
      "    insertionSort(arr, i, Math.min(i + RUN - 1, n - 1));",
      "  }",
      "  for (let size = RUN; size < n; size = 2 * size) {",
      "    for (let left = 0; left < n; left += 2 * size) {",
      "      let mid = left + size - 1;",
      "      let right = Math.min(left + 2 * size - 1, n - 1);",
      "      if (mid < right) merge(arr, left, mid, right);",
      "    }",
      "  }",
      "}"
    ],
    python: [
      "RUN = 32",
      "def tim_sort(arr):",
      "    n = len(arr)",
      "    for i in range(0, n, RUN):",
      "        insertion_sort(arr, i, min((i + 31), (n - 1)))",
      "    size = RUN",
      "    while size < n:",
      "        for left in range(0, n, 2 * size):",
      "            mid = left + size - 1",
      "            right = min((left + 2 * size - 1), (n - 1))",
      "            if mid < right:",
      "                merge(arr, left, mid, right)",
      "        size = 2 * size"
    ],
    java: [
      "static int MIN_MERGE = 32;",
      "public static void timSort(int[] arr, int n) {",
      "    for (int i = 0; i < n; i += MIN_MERGE) {",
      "        insertionSort(arr, i, Math.min((i + MIN_MERGE - 1), (n - 1)));",
      "    }",
      "    for (int size = MIN_MERGE; size < n; size = 2 * size) {",
      "        for (int left = 0; left < n; left += 2 * size) {",
      "            int mid = left + size - 1;",
      "            int right = Math.min((left + 2 * size - 1), (n - 1));",
      "            if (mid < right)",
      "                merge(arr, left, mid, right);",
      "        }",
      "    }",
      "}"
    ],
    cpp: [
      "const int RUN = 32;",
      "void timSort(int arr[], int n) {",
      "    for (int i = 0; i < n; i += RUN)",
      "        insertionSort(arr, i, min((i + RUN - 1), (n - 1)));",
      "    for (int size = RUN; size < n; size = 2 * size) {",
      "        for (int left = 0; left < n; left += 2 * size) {",
      "            int mid = left + size - 1;",
      "            int right = min((left + 2 * size - 1), (n - 1));",
      "            if (mid < right)",
      "                merge(arr, left, mid, right);",
      "        }",
      "    }",
      "}"
    ],
    c: [
      "#define RUN 32",
      "void timSort(int arr[], int n) {",
      "    for (int i = 0; i < n; i += RUN)",
      "        insertionSort(arr, i, min((i + RUN - 1), (n - 1)));",
      "    for (int size = RUN; size < n; size = 2 * size) {",
      "        for (int left = 0; left < n; left += 2 * size) {",
      "            int mid = left + size - 1;",
      "            int right = min((left + 2 * size - 1), (n - 1));",
      "            if (mid < right)",
      "                merge(arr, left, mid, right);",
      "        }",
      "    }",
      "}"
    ],
    typescript: [
      "const RUN = 32;",
      "function timSort(arr: number[], n: number = arr.length): void {",
      "  for (let i = 0; i < n; i += RUN) {",
      "    insertionSort(arr, i, Math.min(i + RUN - 1, n - 1));",
      "  }",
      "  for (let size = RUN; size < n; size = 2 * size) {",
      "    for (let left = 0; left < n; left += 2 * size) {",
      "      let mid = left + size - 1;",
      "      let right = Math.min(left + 2 * size - 1, n - 1);",
      "      if (mid < right) merge(arr, left, mid, right);",
      "    }",
      "  }",
      "}"
    ],
    go: [
      "const RUN = 32",
      "func timSort(arr []int) {",
      "    n := len(arr)",
      "    for i := 0; i < n; i += RUN {",
      "        end := i + RUN - 1",
      "        if end > n-1 { end = n-1 }",
      "        insertionSort(arr, i, end)",
      "    }",
      "    for size := RUN; size < n; size *= 2 {",
      "        for left := 0; left < n; left += 2 * size {",
      "            mid := left + size - 1",
      "            right := left + 2*size - 1",
      "            if right > n-1 { right = n-1 }",
      "            if mid < right {",
      "                merge(arr, left, mid, right)",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    php: [
      "function timSort(array &$arr): void {",
      "    $n = count($arr);",
      "    $RUN = 32;",
      "    for ($i = 0; $i < $n; $i += $RUN) {",
      "        insertionSort($arr, $i, min($i + $RUN - 1, $n - 1));",
      "    }",
      "    for ($size = $RUN; $size < $n; $size = 2 * $size) {",
      "        for ($left = 0; $left < $n; $left += 2 * $size) {",
      "            $mid = $left + $size - 1;",
      "            $right = min($left + 2 * $size - 1, $n - 1);",
      "            if ($mid < $right) {",
      "                merge($arr, $left, $mid, $right);",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    rust: [
      "const RUN: usize = 32;",
      "fn tim_sort(arr: &mut [i32]) {",
      "    let len = arr.len();",
      "    for i in (0..len).step_by(RUN) {",
      "        let end = std::cmp::min(i + RUN - 1, len - 1);",
      "        insertion_sort_range(arr, i, end);",
      "    }",
      "    let mut size = RUN;",
      "    while size < len {",
      "        for left in (0..len).step_by(2 * size) {",
      "            let mid = left + size - 1;",
      "            let right = std::cmp::min(left + 2 * size - 1, len - 1);",
      "            if mid < right {",
      "                merge(arr, left, mid, right);",
      "            }",
      "        }",
      "        size *= 2;",
      "    }",
      "}"
    ]
  },
  introSort: {
    pseudocode: [
      "function introsort(arr, begin, end, depth_limit):",
      "  if size <= 1: return",
      "  if depth_limit == 0:",
      "    heapsort(arr, begin, end)",
      "    return",
      "  pivot = partition(arr, begin, end)",
      "  introsort(arr, begin, pivot-1, depth_limit - 1)",
      "  introsort(arr, pivot+1, end, depth_limit - 1)"
    ],
    javascript: [
      "function introSort(arr) {",
      "  let depthLimit = 2 * Math.floor(Math.log2(arr.length));",
      "  introSortRecursive(arr, 0, arr.length - 1, depthLimit);",
      "}",
      "function introSortRecursive(arr, begin, end, depthLimit) {",
      "  if (end - begin < 1) return;",
      "  if (depthLimit === 0) {",
      "    heapSortSubarray(arr, begin, end);",
      "    return;",
      "  }",
      "  let pivot = partition(arr, begin, end);",
      "  introSortRecursive(arr, begin, pivot - 1, depthLimit - 1);",
      "  introSortRecursive(arr, pivot + 1, end, depthLimit - 1);",
      "}"
    ],
    python: [
      "import math",
      "def intro_sort(arr):",
      "    depth_limit = 2 * math.floor(math.log2(len(arr)))",
      "    intro_sort_recursive(arr, 0, len(arr) - 1, depth_limit)",
      "def intro_sort_recursive(arr, begin, end, depth_limit):",
      "    if end - begin < 1: return",
      "    if depth_limit == 0:",
      "        heap_sort_subarray(arr, begin, end)",
      "        return",
      "    pivot = partition(arr, begin, end)",
      "    intro_sort_recursive(arr, begin, pivot - 1, depth_limit - 1)",
      "    intro_sort_recursive(arr, pivot + 1, end, depth_limit - 1)"
    ],
    java: [
      "public void introSort(int[] arr) {",
      "    int depthLimit = (int)(2 * Math.floor(Math.log(arr.length) / Math.log(2)));",
      "    introSortRecursive(arr, 0, arr.length - 1, depthLimit);",
      "}",
      "private void introSortRecursive(int[] arr, int begin, int end, int depthLimit) {",
      "    if (end - begin < 1) return;",
      "    if (depthLimit == 0) {",
      "        heapSortSubarray(arr, begin, end);",
      "        return;",
      "    }",
      "    int pivot = partition(arr, begin, end);",
      "    introSortRecursive(arr, begin, pivot - 1, depthLimit - 1);",
      "    introSortRecursive(arr, pivot + 1, end, depthLimit - 1);",
      "}"
    ],
    cpp: [
      "void introSort(int arr[], int n) {",
      "    int depthLimit = 2 * log2(n);",
      "    introSortRecursive(arr, 0, n - 1, depthLimit);",
      "}",
      "void introSortRecursive(int arr[], int begin, int end, int depthLimit) {",
      "    if (end - begin < 1) return;",
      "    if (depthLimit == 0) {",
      "        heapSortSubarray(arr, begin, end);",
      "        return;",
      "    }",
      "    int pivot = partition(arr, begin, end);",
      "    introSortRecursive(arr, begin, pivot - 1, depthLimit - 1);",
      "    introSortRecursive(arr, pivot + 1, end, depthLimit - 1);",
      "}"
    ],
    c: [
      "void introSort(int arr[], int n) {",
      "    int depthLimit = 2 * log(n) / log(2);",
      "    introSortRecursive(arr, 0, n - 1, depthLimit);",
      "}",
      "void introSortRecursive(int arr[], int begin, int end, int depthLimit) {",
      "    if (end - begin < 1) return;",
      "    if (depthLimit == 0) {",
      "        heapSortSubarray(arr, begin, end);",
      "        return;",
      "    }",
      "    int pivot = partition(arr, begin, end);",
      "    introSortRecursive(arr, begin, pivot - 1, depthLimit - 1);",
      "    introSortRecursive(arr, pivot + 1, end, depthLimit - 1);",
      "}"
    ],
    typescript: [
      "function introSort(arr: number[]): void {",
      "  let depthLimit = 2 * Math.floor(Math.log2(arr.length));",
      "  introSortRecursive(arr, 0, arr.length - 1, depthLimit);",
      "}",
      "function introSortRecursive(arr: number[], begin: number, end: number, depthLimit: number): void {",
      "  if (end - begin < 1) return;",
      "  if (depthLimit === 0) {",
      "    heapSortSubarray(arr, begin, end);",
      "    return;",
      "  }",
      "  let pivot = partition(arr, begin, end);",
      "  introSortRecursive(arr, begin, pivot - 1, depthLimit - 1);",
      "  introSortRecursive(arr, pivot + 1, end, depthLimit - 1);",
      "}"
    ],
    go: [
      "import \"math\"",
      "func introSort(arr []int) {",
      "    depthLimit := 2 * int(math.Log2(float64(len(arr))))",
      "    introSortRecursive(arr, 0, len(arr)-1, depthLimit)",
      "}",
      "func introSortRecursive(arr []int, begin, end, depthLimit int) {",
      "    if end-begin < 1 { return }",
      "    if depthLimit == 0 {",
      "        heapSortSubarray(arr, begin, end)",
      "        return",
      "    }",
      "    pivot := partition(arr, begin, end)",
      "    introSortRecursive(arr, begin, pivot-1, depthLimit-1)",
      "    introSortRecursive(arr, pivot+1, end, depthLimit-1)",
      "}"
    ],
    php: [
      "function introSort(array &$arr): void {",
      "    $depthLimit = 2 * floor(log(count($arr), 2));",
      "    introSortRecursive($arr, 0, count($arr) - 1, $depthLimit);",
      "}",
      "function introSortRecursive(array &$arr, int $begin, int $end, int $depthLimit): void {",
      "    if ($end - $begin < 1) return;",
      "    if ($depthLimit == 0) {",
      "        heapSortSubarray($arr, $begin, $end);",
      "        return;",
      "    }",
      "    $pivot = partition($arr, $begin, $end);",
      "    introSortRecursive($arr, $begin, $pivot - 1, $depthLimit - 1);",
      "    introSortRecursive($arr, $pivot + 1, $end, $depthLimit - 1);",
      "}"
    ],
    rust: [
      "fn intro_sort(arr: &mut [i32]) {",
      "    let len = arr.len();",
      "    if len <= 1 { return; }",
      "    let depth_limit = 2 * (len as f64).log2().floor() as usize;",
      "    intro_sort_recursive(arr, 0, len - 1, depth_limit);",
      "}",
      "fn intro_sort_recursive(arr: &mut [i32], begin: usize, end: usize, depth_limit: usize) {",
      "    if end <= begin { return; }",
      "    if depth_limit == 0 {",
      "        heap_sort_subarray(arr, begin, end);",
      "        return;",
      "    }",
      "    let pivot = partition(arr, begin, end);",
      "    if pivot > 0 { intro_sort_recursive(arr, begin, pivot - 1, depth_limit - 1); }",
      "    intro_sort_recursive(arr, pivot + 1, end, depth_limit - 1);",
      "}"
    ]
  }
};

export const sortingExamples: Record<string, string> = {
  bubbleSort: "A teacher physically sorting a row of students by height by swapping two adjacent standing students until they are aligned from shortest to tallest.",
  selectionSort: "A card player selecting the lowest value card from their hand, swapping it with the first card, then repeating for the remaining cards.",
  insertionSort: "Sorting a hand of playing cards: you pick up a card from the table, compare it to cards already in your hand, and slide it directly into its sorted spot.",
  mergeSortWrapper: "E-Commerce sites sorting millions of items by 'Rating' and then 'Price'. Because Merge Sort is stable, sorting by price preserves the rating order.",
  quickSortWrapper: "Organizing files inside a hard drive database index or sorting in-memory system arrays inside highly optimized codebases like V8.",
  heapSort: "An operating system executing CPU tasks where the task with the highest priority must always be popped out first in O(1) time.",
  shellSort: "Sorting inventory counts in a low-resource smart thermostat or IoT device with only 2KB of RAM, where Quick Sort's recursion would overflow memory.",
  cocktailSort: "Tidying a bookshelf where almost all books are sorted, but a few heavy textbooks at the end need to travel back to the beginning of the shelf.",
  combSort: "Cleaning up sensor logging datasets on low-power microcontrollers before transmitting data packets to a central server.",
  gnomeSort: "A garden gnome walking to the next flowerpot, comparing it with the previous, swapping them if needed, and stepping back to verify ordering.",
  oddEvenSort: "A parallel GPU sorting block where adjacent elements at odd/even pixel locations are processed simultaneously across 1000 rendering cores.",
  pancakeSort: "A sorting machine stacker adjusting a pile of heavy wooden pallets by slipping a forklift under a segment and flipping the sub-stack over.",
  bitonicSortWrapper: "An FPGA graphics acceleration card running a network of wire comparisons in parallel blocks for real-time video buffer stream sorting.",
  radixSort: "Sorting a mailing list of 100,000 envelopes by their 5-digit ZIP codes, sorting them first by the 5th digit, then the 4th, up to the 1st digit.",
  stoogeSortWrapper: "Used as a theoretical warning example in computer science textbooks to show how recursion can go disastrously wrong.",
  bogoSort: "Sorting a deck of cards by throwing them in the air, picking them up randomly, and checking if they landed in perfect sorted order.",
  timSort: "Organizing a large bookshelf by first sorting small chunks of books manually (Insertion sort), and then systematically merging the sorted chunks together.",
  introSort: "A team rapidly dividing a massive pile of files into smaller piles (Quick sort), but if a pile takes too long to divide, a specialist steps in to precisely sort it (Heap sort)."
};

export function getCodeSnippetForAlgo(algoKey: string, lang: string): string {
  const block = sortingCodeBlocks[algoKey];
  if (!block) return `// Code implementation for ${algoKey} in ${lang.toUpperCase()}`;

  const langKey = lang.toLowerCase();
  
  if (langKey === "typescript") {
    if (block.typescript) return block.typescript.join("\n");
    // Generate idiomatic TypeScript from JavaScript
    return block.javascript.join("\n")
      .replace(/function (\w+)\(arr\)/g, "function $1(arr: number[]): number[]")
      .replace(/let n = arr\.length;/g, "const n: number = arr.length;")
      .replace(/let (\w+) = ([^;]+);/g, "let $1: number = $2;");
  }

  if (langKey === "go") {
    if (block.go) return block.go.join("\n");
    return [
      `package main`,
      ``,
      `import "fmt"`,
      ``,
      `func ${algoKey}(arr []int) []int {`,
      `    n := len(arr)`,
      `    for i := 0; i < n-1; i++ {`,
      `        for j := 0; j < n-i-1; j++ {`,
      `            if arr[j] > arr[j+1] {`,
      `                arr[j], arr[j+1] = arr[j+1], arr[j]`,
      `            }`,
      `        }`,
      `    }`,
      `    return arr`,
      `}`,
      ``,
      `func main() {`,
      `    arr := []int{5, 2, 9, 1, 5, 6}`,
      `    fmt.Println("Sorted:", ${algoKey}(arr))`,
      `}`
    ].join("\n");
  }

  if (langKey === "php") {
    if (block.php) return block.php.join("\n");
    return [
      `<?php`,
      `function ${algoKey}(array &$arr): array {`,
      `    $n = count($arr);`,
      `    for ($i = 0; $i < $n - 1; $i++) {`,
      `        for ($j = 0; $j < $n - $i - 1; $j++) {`,
      `            if ($arr[$j] > $arr[$j + 1]) {`,
      `                $temp = $arr[$j];`,
      `                $arr[$j] = $arr[$j + 1];`,
      `                $arr[$j + 1] = $temp;`,
      `            }`,
      `        }`,
      `    }`,
      `    return $arr;`,
      `}`,
      `?>`
    ].join("\n");
  }

  if (langKey === "rust") {
    if (block.rust) return block.rust.join("\n");
    return [
      `pub fn ${algoKey}(arr: &mut [i32]) {`,
      `    let n = arr.len();`,
      `    for i in 0..n {`,
      `        for j in 0..n - i - 1 {`,
      `            if arr[j] > arr[j + 1] {`,
      `                arr.swap(j, j + 1);`,
      `            }`,
      `        }`,
      `    }`,
      `}`,
      ``,
      `fn main() {`,
      `    let mut numbers = vec![5, 2, 9, 1, 5, 6];`,
      `    ${algoKey}(&mut numbers);`,
      `    println!("Sorted: {:?}", numbers);`,
      `}`
    ].join("\n");
  }

  const result = (block as unknown as Record<string, string[]>)[langKey];
  if (result && Array.isArray(result)) {
    return result.join("\n");
  }

  return block.javascript ? block.javascript.join("\n") : `// ${lang.toUpperCase()} implementation for ${algoKey}`;
}
