export interface CodeImplementation {
  pseudocode: string[];
  javascript: string[];
  python: string[];
  java: string[];
  cpp: string[];
  c: string[];
}

export const sortingCodeBlocks: Record<string, CodeImplementation> = {
  bubbleSort: {
    pseudocode: [
      "for i from 0 to n-1:",
      "  for j from 0 to n-i-1:",
      "    if arr[j] > arr[j+1]:",
      "      swap(arr[j], arr[j+1])"
    ],
    javascript: [
      "function bubbleSort(arr) {",
      "  let n = arr.length;",
      "  for (let i = 0; i < n - 1; i++) {",
      "    for (let j = 0; j < n - i - 1; j++) {",
      "      if (arr[j] > arr[j + 1]) {",
      "        [arr[j], arr[j + 1]] = [arr[j + 1], arr[j]];",
      "      }",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def bubble_sort(arr):",
      "    n = len(arr)",
      "    for i in range(n - 1):",
      "        for j in range(n - i - 1):",
      "            if arr[j] > arr[j + 1]:",
      "                arr[j], arr[j + 1] = arr[j + 1], arr[j]",
      "    return arr"
    ],
    java: [
      "public static void bubbleSort(int[] arr) {",
      "    int n = arr.length;",
      "    for (int i = 0; i < n - 1; i++) {",
      "        for (int j = 0; j < n - i - 1; j++) {",
      "            if (arr[j] > arr[j + 1]) {",
      "                int temp = arr[j];",
      "                arr[j] = arr[j + 1];",
      "                arr[j + 1] = temp;",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    cpp: [
      "void bubbleSort(int arr[], int n) {",
      "    for (int i = 0; i < n - 1; i++) {",
      "        for (int j = 0; j < n - i - 1; j++) {",
      "            if (arr[j] > arr[j + 1]) {",
      "                std::swap(arr[j], arr[j + 1]);",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    c: [
      "void bubbleSort(int arr[], int n) {",
      "    for (int i = 0; i < n - 1; i++) {",
      "        for (int j = 0; j < n - i - 1; j++) {",
      "            if (arr[j] > arr[j + 1]) {",
      "                int temp = arr[j];",
      "                arr[j] = arr[j + 1];",
      "                arr[j + 1] = temp;",
      "            }",
      "        }",
      "    }",
      "}"
    ]
  },
  selectionSort: {
    pseudocode: [
      "for i from 0 to n-1:",
      "  min_idx = i",
      "  for j from i+1 to n:",
      "    if arr[j] < arr[min_idx]:",
      "      min_idx = j",
      "  swap(arr[i], arr[min_idx])"
    ],
    javascript: [
      "function selectionSort(arr) {",
      "  let n = arr.length;",
      "  for (let i = 0; i < n - 1; i++) {",
      "    let minIdx = i;",
      "    for (let j = i + 1; j < n; j++) {",
      "      if (arr[j] < arr[minIdx]) minIdx = j;",
      "    }",
      "    [arr[i], arr[minIdx]] = [arr[minIdx], arr[i]];",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def selection_sort(arr):",
      "    n = len(arr)",
      "    for i in range(n - 1):",
      "        min_idx = i",
      "        for j in range(i + 1, n):",
      "            if arr[j] < arr[min_idx]:",
      "                min_idx = j",
      "        arr[i], arr[min_idx] = arr[min_idx], arr[i]",
      "    return arr"
    ],
    java: [
      "public static void selectionSort(int[] arr) {",
      "    int n = arr.length;",
      "    for (int i = 0; i < n - 1; i++) {",
      "        int minIdx = i;",
      "        for (int j = i + 1; j < n; j++) {",
      "            if (arr[j] < arr[minIdx]) minIdx = j;",
      "        }",
      "        int temp = arr[minIdx];",
      "        arr[minIdx] = arr[i];",
      "        arr[i] = temp;",
      "    }",
      "}"
    ],
    cpp: [
      "void selectionSort(int arr[], int n) {",
      "    for (int i = 0; i < n - 1; i++) {",
      "        int minIdx = i;",
      "        for (int j = i + 1; j < n; j++) {",
      "            if (arr[j] < arr[minIdx]) minIdx = j;",
      "        }",
      "        std::swap(arr[i], arr[minIdx]);",
      "    }",
      "}"
    ],
    c: [
      "void selectionSort(int arr[], int n) {",
      "    for (int i = 0; i < n - 1; i++) {",
      "        int minIdx = i;",
      "        for (int j = i + 1; j < n; j++) {",
      "            if (arr[j] < arr[minIdx]) minIdx = j;",
      "        }",
      "        int temp = arr[minIdx];",
      "        arr[minIdx] = arr[i];",
      "        arr[i] = temp;",
      "    }",
      "}"
    ]
  },
  insertionSort: {
    pseudocode: [
      "for i from 1 to n-1:",
      "  key = arr[i]",
      "  j = i - 1",
      "  while j >= 0 and arr[j] > key:",
      "    arr[j+1] = arr[j]",
      "    j = j - 1",
      "  arr[j+1] = key"
    ],
    javascript: [
      "function insertionSort(arr) {",
      "  let n = arr.length;",
      "  for (let i = 1; i < n; i++) {",
      "    let key = arr[i];",
      "    let j = i - 1;",
      "    while (j >= 0 && arr[j] > key) {",
      "      arr[j + 1] = arr[j];",
      "      j--;",
      "    }",
      "    arr[j + 1] = key;",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def insertion_sort(arr):",
      "    for i in range(1, len(arr)):",
      "        key = arr[i]",
      "        j = i - 1",
      "        while j >= 0 and arr[j] > key:",
      "            arr[j + 1] = arr[j]",
      "            j -= 1",
      "        arr[j + 1] = key",
      "    return arr"
    ],
    java: [
      "public static void insertionSort(int[] arr) {",
      "    int n = arr.length;",
      "    for (int i = 1; i < n; i++) {",
      "        int key = arr[i];",
      "        int j = i - 1;",
      "        while (j >= 0 && arr[j] > key) {",
      "            arr[j + 1] = arr[j];",
      "            j--;",
      "        }",
      "        arr[j + 1] = key;",
      "    }",
      "}"
    ],
    cpp: [
      "void insertionSort(int arr[], int n) {",
      "    for (int i = 1; i < n; i++) {",
      "        int key = arr[i];",
      "        int j = i - 1;",
      "        while (j >= 0 && arr[j] > key) {",
      "            arr[j + 1] = arr[j];",
      "            j--;",
      "        }",
      "        arr[j + 1] = key;",
      "    }",
      "}"
    ],
    c: [
      "void insertionSort(int arr[], int n) {",
      "    for (int i = 1; i < n; i++) {",
      "        int key = arr[i];",
      "        int j = i - 1;",
      "        while (j >= 0 && arr[j] > key) {",
      "            arr[j + 1] = arr[j];",
      "            j--;",
      "        }",
      "        arr[j + 1] = key;",
      "    }",
      "}"
    ]
  },
  mergeSortWrapper: {
    pseudocode: [
      "function mergeSort(arr):",
      "  if length(arr) <= 1: return arr",
      "  mid = length(arr) / 2",
      "  left = mergeSort(arr[0:mid])",
      "  right = mergeSort(arr[mid:])",
      "  return merge(left, right)"
    ],
    javascript: [
      "function mergeSort(arr) {",
      "  if (arr.length <= 1) return arr;",
      "  const mid = Math.floor(arr.length / 2);",
      "  const left = mergeSort(arr.slice(0, mid));",
      "  const right = mergeSort(arr.slice(mid));",
      "  return merge(left, right);",
      "}"
    ],
    python: [
      "def merge_sort(arr):",
      "    if len(arr) <= 1: return arr",
      "    mid = len(arr) // 2",
      "    left = merge_sort(arr[:mid])",
      "    right = merge_sort(arr[mid:])",
      "    return merge(left, right)"
    ],
    java: [
      "public static void mergeSort(int[] arr, int l, int r) {",
      "    if (l < r) {",
      "        int m = l + (r - l) / 2;",
      "        mergeSort(arr, l, m);",
      "        mergeSort(arr, m + 1, r);",
      "        merge(arr, l, m, r);",
      "    }",
      "}"
    ],
    cpp: [
      "void mergeSort(int arr[], int l, int r) {",
      "    if (l < r) {",
      "        int m = l + (r - l) / 2;",
      "        mergeSort(arr, l, m);",
      "        mergeSort(arr, m + 1, r);",
      "        merge(arr, l, m, r);",
      "    }",
      "}"
    ],
    c: [
      "void mergeSort(int arr[], int l, int r) {",
      "    if (l < r) {",
      "        int m = l + (r - l) / 2;",
      "        mergeSort(arr, l, m);",
      "        mergeSort(arr, m + 1, r);",
      "        merge(arr, l, m, r);",
      "    }",
      "}"
    ]
  },
  quickSortWrapper: {
    pseudocode: [
      "function quickSort(arr, low, high):",
      "  if low < high:",
      "    pi = partition(arr, low, high)",
      "    quickSort(arr, low, pi-1)",
      "    quickSort(arr, pi+1, high)"
    ],
    javascript: [
      "function quickSort(arr, low = 0, high = arr.length - 1) {",
      "  if (low < high) {",
      "    let pi = partition(arr, low, high);",
      "    quickSort(arr, low, pi - 1);",
      "    quickSort(arr, pi + 1, high);",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def quick_sort(arr, low, high):",
      "    if low < high:",
      "        pi = partition(arr, low, high)",
      "        quick_sort(arr, low, pi - 1)",
      "        quick_sort(arr, pi + 1, high)"
    ],
    java: [
      "public static void quickSort(int[] arr, int low, int high) {",
      "    if (low < high) {",
      "        int pi = partition(arr, low, high);",
      "        quickSort(arr, low, pi - 1);",
      "        quickSort(arr, pi + 1, high);",
      "    }",
      "}"
    ],
    cpp: [
      "void quickSort(int arr[], int low, int high) {",
      "    if (low < high) {",
      "        int pi = partition(arr, low, high);",
      "        quickSort(arr, low, pi - 1);",
      "        quickSort(arr, pi + 1, high);",
      "    }",
      "}"
    ],
    c: [
      "void quickSort(int arr[], int low, int high) {",
      "    if (low < high) {",
      "        int pi = partition(arr, low, high);",
      "        quickSort(arr, low, pi - 1);",
      "        quickSort(arr, pi + 1, high);",
      "    }",
      "}"
    ]
  },
  heapSort: {
    pseudocode: [
      "function heapSort(arr):",
      "  buildMaxHeap(arr)",
      "  for i from n-1 to 1:",
      "    swap(arr[0], arr[i])",
      "    heapify(arr, 0, i)"
    ],
    javascript: [
      "function heapSort(arr) {",
      "  let n = arr.length;",
      "  for (let i = Math.floor(n / 2) - 1; i >= 0; i--) heapify(arr, n, i);",
      "  for (let i = n - 1; i > 0; i--) {",
      "    [arr[0], arr[i]] = [arr[i], arr[0]];",
      "    heapify(arr, i, 0);",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def heap_sort(arr):",
      "    n = len(arr)",
      "    for i in range(n // 2 - 1, -1, -1): heapify(arr, n, i)",
      "    for i in range(n - 1, 0, -1):",
      "        arr[0], arr[i] = arr[i], arr[0]",
      "        heapify(arr, i, 0)",
      "    return arr"
    ],
    java: [
      "public static void heapSort(int[] arr) {",
      "    int n = arr.length;",
      "    for (int i = n / 2 - 1; i >= 0; i--) heapify(arr, n, i);",
      "    for (int i = n - 1; i > 0; i--) {",
      "        int temp = arr[0]; arr[0] = arr[i]; arr[i] = temp;",
      "        heapify(arr, i, 0);",
      "    }",
      "}"
    ],
    cpp: [
      "void heapSort(int arr[], int n) {",
      "    for (int i = n / 2 - 1; i >= 0; i--) heapify(arr, n, i);",
      "    for (int i = n - 1; i > 0; i--) {",
      "        std::swap(arr[0], arr[i]);",
      "        heapify(arr, i, 0);",
      "    }",
      "}"
    ],
    c: [
      "void heapSort(int arr[], int n) {",
      "    for (int i = n / 2 - 1; i >= 0; i--) heapify(arr, n, i);",
      "    for (int i = n - 1; i > 0; i--) {",
      "        int temp = arr[0]; arr[0] = arr[i]; arr[i] = temp;",
      "        heapify(arr, i, 0);",
      "    }",
      "}"
    ]
  },
  shellSort: {
    pseudocode: [
      "gap = n / 2",
      "while gap > 0:",
      "  for i from gap to n:",
      "    temp = arr[i]",
      "    j = i",
      "    while j >= gap and arr[j-gap] > temp:",
      "      arr[j] = arr[j-gap]",
      "    arr[j] = temp",
      "  gap = gap / 2"
    ],
    javascript: [
      "function shellSort(arr) {",
      "  let n = arr.length;",
      "  for (let gap = Math.floor(n / 2); gap > 0; gap = Math.floor(gap / 2)) {",
      "    for (let i = gap; i < n; i++) {",
      "      let temp = arr[i];",
      "      let j;",
      "      for (j = i; j >= gap && arr[j - gap] > temp; j -= gap) {",
      "        arr[j] = arr[j - gap];",
      "      }",
      "      arr[j] = temp;",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def shell_sort(arr):",
      "    n = len(arr)",
      "    gap = n // 2",
      "    while gap > 0:",
      "        for i in range(gap, n):",
      "            temp = arr[i]",
      "            j = i",
      "            while j >= gap and arr[j - gap] > temp:",
      "                arr[j] = arr[j - gap]",
      "                j -= gap",
      "            arr[j] = temp",
      "        gap //= 2",
      "    return arr"
    ],
    java: [
      "public static void shellSort(int[] arr) {",
      "    int n = arr.length;",
      "    for (int gap = n / 2; gap > 0; gap /= 2) {",
      "        for (int i = gap; i < n; i++) {",
      "            int temp = arr[i];",
      "            int j;",
      "            for (j = i; j >= gap && arr[j - gap] > temp; j -= gap) {",
      "                arr[j] = arr[j - gap];",
      "            }",
      "            arr[j] = temp;",
      "        }",
      "    }",
      "}"
    ],
    cpp: [
      "void shellSort(int arr[], int n) {",
      "    for (int gap = n / 2; gap > 0; gap /= 2) {",
      "        for (int i = gap; i < n; i++) {",
      "            int temp = arr[i];",
      "            int j;",
      "            for (j = i; j >= gap && arr[j - gap] > temp; j -= gap) {",
      "                arr[j] = arr[j - gap];",
      "            }",
      "            arr[j] = temp;",
      "        }",
      "    }",
      "}"
    ],
    c: [
      "void shellSort(int arr[], int n) {",
      "    for (int gap = n / 2; gap > 0; gap /= 2) {",
      "        for (int i = gap; i < n; i++) {",
      "            int temp = arr[i];",
      "            int j;",
      "            for (j = i; j >= gap && arr[j - gap] > temp; j -= gap) {",
      "                arr[j] = arr[j - gap];",
      "            }",
      "            arr[j] = temp;",
      "        }",
      "    }",
      "}"
    ]
  },
  cocktailSort: {
    pseudocode: [
      "do:",
      "  swapped = false",
      "  for i from 0 to n-1:",
      "    if arr[i] > arr[i+1]: swap and set swapped",
      "  for i from n-1 to 0:",
      "    if arr[i] > arr[i+1]: swap and set swapped",
      "while swapped"
    ],
    javascript: [
      "function cocktailSort(arr) {",
      "  let swapped = true;",
      "  let start = 0, end = arr.length - 1;",
      "  while (swapped) {",
      "    swapped = false;",
      "    for (let i = start; i < end; i++) {",
      "      if (arr[i] > arr[i + 1]) {",
      "        [arr[i], arr[i + 1]] = [arr[i + 1], arr[i]];",
      "        swapped = true;",
      "      }",
      "    }",
      "    if (!swapped) break;",
      "    swapped = false;",
      "    end--;",
      "    for (let i = end - 1; i >= start; i--) {",
      "      if (arr[i] > arr[i + 1]) {",
      "        [arr[i], arr[i + 1]] = [arr[i + 1], arr[i]];",
      "        swapped = true;",
      "      }",
      "    }",
      "    start++;",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def cocktail_sort(arr):",
      "    n = len(arr)",
      "    swapped = True",
      "    start, end = 0, n - 1",
      "    while swapped:",
      "        swapped = False",
      "        for i in range(start, end):",
      "            if arr[i] > arr[i + 1]:",
      "                arr[i], arr[i + 1] = arr[i + 1], arr[i]",
      "                swapped = True",
      "        if not swapped: break",
      "        swapped = False",
      "        end -= 1",
      "        for i in range(end - 1, start - 1, -1):",
      "            if arr[i] > arr[i + 1]:",
      "                arr[i], arr[i + 1] = arr[i + 1], arr[i]",
      "                swapped = True",
      "        start += 1",
      "    return arr"
    ],
    java: [
      "public static void cocktailSort(int[] arr) {",
      "    boolean swapped = true;",
      "    int start = 0, end = arr.length - 1;",
      "    while (swapped) {",
      "        swapped = false;",
      "        for (int i = start; i < end; i++) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                swapped = true;",
      "            }",
      "        }",
      "        if (!swapped) break;",
      "        swapped = false;",
      "        end--;",
      "        for (int i = end - 1; i >= start; i--) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                swapped = true;",
      "            }",
      "        }",
      "        start++;",
      "    }",
      "}"
    ],
    cpp: [
      "void cocktailSort(int arr[], int n) {",
      "    bool swapped = true;",
      "    int start = 0, end = n - 1;",
      "    while (swapped) {",
      "        swapped = false;",
      "        for (int i = start; i < end; ++i) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                std::swap(arr[i], arr[i + 1]);",
      "                swapped = true;",
      "            }",
      "        }",
      "        if (!swapped) break;",
      "        swapped = false;",
      "        --end;",
      "        for (int i = end - 1; i >= start; --i) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                std::swap(arr[i], arr[i + 1]);",
      "                swapped = true;",
      "            }",
      "        }",
      "        ++start;",
      "    }",
      "}"
    ],
    c: [
      "void cocktailSort(int arr[], int n) {",
      "    int swapped = 1;",
      "    int start = 0, end = n - 1;",
      "    while (swapped) {",
      "        swapped = 0;",
      "        for (int i = start; i < end; ++i) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                swapped = 1;",
      "            }",
      "        }",
      "        if (!swapped) break;",
      "        swapped = 0;",
      "        --end;",
      "        for (int i = end - 1; i >= start; --i) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                swapped = 1;",
      "            }",
      "        }",
      "        ++start;",
      "    }",
      "}"
    ]
  },
  combSort: {
    pseudocode: [
      "gap = n",
      "shrink = 1.3",
      "while gap > 1:",
      "  gap = floor(gap / shrink)",
      "  for i from 0 to n-gap:",
      "    if arr[i] > arr[i+gap]:",
      "      swap(arr[i], arr[i+gap])"
    ],
    javascript: [
      "function combSort(arr) {",
      "  let n = arr.length;",
      "  let gap = n;",
      "  let shrink = 1.3;",
      "  let sorted = false;",
      "  while (gap > 1 || !sorted) {",
      "    gap = Math.floor(gap / shrink);",
      "    if (gap < 1) gap = 1;",
      "    sorted = true;",
      "    for (let i = 0; i + gap < n; i++) {",
      "      if (arr[i] > arr[i + gap]) {",
      "        [arr[i], arr[i + gap]] = [arr[i + gap], arr[i]];",
      "        sorted = false;",
      "      }",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def comb_sort(arr):",
      "    n = len(arr)",
      "    gap = n",
      "    shrink = 1.3",
      "    sorted = False",
      "    while gap > 1 or not sorted:",
      "        gap = int(gap / shrink)",
      "        if gap < 1: gap = 1",
      "        sorted = True",
      "        for i in range(0, n - gap):",
      "            if arr[i] > arr[i + gap]:",
      "                arr[i], arr[i + gap] = arr[i + gap], arr[i]",
      "                sorted = False",
      "    return arr"
    ],
    java: [
      "public static void combSort(int[] arr) {",
      "    int n = arr.length;",
      "    int gap = n;",
      "    float shrink = 1.3f;",
      "    boolean swapped = true;",
      "    while (gap > 1 || swapped) {",
      "        gap = (int)(gap / shrink);",
      "        if (gap < 1) gap = 1;",
      "        swapped = false;",
      "        for (int i = 0; i + gap < n; i++) {",
      "            if (arr[i] > arr[i + gap]) {",
      "                int temp = arr[i]; arr[i] = arr[i + gap]; arr[i + gap] = temp;",
      "                swapped = true;",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    cpp: [
      "void combSort(int arr[], int n) {",
      "    int gap = n;",
      "    float shrink = 1.3;",
      "    bool swapped = true;",
      "    while (gap > 1 || swapped) {",
      "        gap = gap / shrink;",
      "        if (gap < 1) gap = 1;",
      "        swapped = false;",
      "        for (int i = 0; i + gap < n; i++) {",
      "            if (arr[i] > arr[i + gap]) {",
      "                std::swap(arr[i], arr[i + gap]);",
      "                swapped = true;",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    c: [
      "void combSort(int arr[], int n) {",
      "    int gap = n;",
      "    float shrink = 1.3;",
      "    int swapped = 1;",
      "    while (gap > 1 || swapped) {",
      "        gap = gap / shrink;",
      "        if (gap < 1) gap = 1;",
      "        swapped = 0;",
      "        for (int i = 0; i + gap < n; i++) {",
      "            if (arr[i] > arr[i + gap]) {",
      "                int temp = arr[i]; arr[i] = arr[i + gap]; arr[i + gap] = temp;",
      "                swapped = 1;",
      "            }",
      "        }",
      "    }",
      "}"
    ]
  },
  gnomeSort: {
    pseudocode: [
      "pos = 0",
      "while pos < n:",
      "  if pos == 0 or arr[pos] >= arr[pos-1]:",
      "    pos = pos + 1",
      "  else:",
      "    swap(arr[pos], arr[pos-1])",
      "    pos = pos - 1"
    ],
    javascript: [
      "function gnomeSort(arr) {",
      "  let n = arr.length;",
      "  let index = 0;",
      "  while (index < n) {",
      "    if (index === 0 || arr[index] >= arr[index - 1]) {",
      "      index++;",
      "    } else {",
      "      [arr[index], arr[index - 1]] = [arr[index - 1], arr[index]];",
      "      index--;",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def gnome_sort(arr):",
      "    n = len(arr)",
      "    index = 0",
      "    while index < n:",
      "        if index == 0 or arr[index] >= arr[index - 1]:",
      "            index += 1",
      "        else:",
      "            arr[index], arr[index - 1] = arr[index - 1], arr[index]",
      "            index -= 1",
      "    return arr"
    ],
    java: [
      "public static void gnomeSort(int[] arr) {",
      "    int n = arr.length;",
      "    int index = 0;",
      "    while (index < n) {",
      "        if (index == 0 || arr[index] >= arr[index - 1]) {",
      "            index++;",
      "        } else {",
      "            int temp = arr[index]; arr[index] = arr[index - 1]; arr[index - 1] = temp;",
      "            index--;",
      "        }",
      "    }",
      "}"
    ],
    cpp: [
      "void gnomeSort(int arr[], int n) {",
      "    int index = 0;",
      "    while (index < n) {",
      "        if (index == 0 || arr[index] >= arr[index - 1]) {",
      "            index++;",
      "        } else {",
      "            std::swap(arr[index], arr[index - 1]);",
      "            index--;",
      "        }",
      "    }",
      "}"
    ],
    c: [
      "void gnomeSort(int arr[], int n) {",
      "    int index = 0;",
      "    while (index < n) {",
      "        if (index == 0 || arr[index] >= arr[index - 1]) {",
      "            index++;",
      "        } else {",
      "            int temp = arr[index]; arr[index] = arr[index - 1]; arr[index - 1] = temp;",
      "            index--;",
      "        }",
      "    }",
      "}"
    ]
  },
  oddEvenSort: {
    pseudocode: [
      "sorted = false",
      "while not sorted:",
      "  sorted = true",
      "  for i in odd indices:",
      "    if arr[i] > arr[i+1]: swap and mark unsorted",
      "  for i in even indices:",
      "    if arr[i] > arr[i+1]: swap and mark unsorted"
    ],
    javascript: [
      "function oddEvenSort(arr) {",
      "  let n = arr.length;",
      "  let sorted = false;",
      "  while (!sorted) {",
      "    sorted = true;",
      "    for (let i = 1; i < n - 1; i += 2) {",
      "      if (arr[i] > arr[i + 1]) {",
      "        [arr[i], arr[i + 1]] = [arr[i + 1], arr[i]];",
      "        sorted = false;",
      "      }",
      "    }",
      "    for (let i = 0; i < n - 1; i += 2) {",
      "      if (arr[i] > arr[i + 1]) {",
      "        [arr[i], arr[i + 1]] = [arr[i + 1], arr[i]];",
      "        sorted = false;",
      "      }",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def odd_even_sort(arr):",
      "    n = len(arr)",
      "    sorted = False",
      "    while not sorted:",
      "        sorted = True",
      "        for i in range(1, n - 1, 2):",
      "            if arr[i] > arr[i + 1]:",
      "                arr[i], arr[i + 1] = arr[i + 1], arr[i]",
      "                sorted = False",
      "        for i in range(0, n - 1, 2):",
      "            if arr[i] > arr[i + 1]:",
      "                arr[i], arr[i + 1] = arr[i + 1], arr[i]",
      "                sorted = False",
      "    return arr"
    ],
    java: [
      "public static void oddEvenSort(int[] arr) {",
      "    int n = arr.length;",
      "    boolean sorted = false;",
      "    while (!sorted) {",
      "        sorted = true;",
      "        for (int i = 1; i < n - 1; i += 2) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                sorted = false;",
      "            }",
      "        }",
      "        for (int i = 0; i < n - 1; i += 2) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                sorted = false;",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    cpp: [
      "void oddEvenSort(int arr[], int n) {",
      "    bool sorted = false;",
      "    while (!sorted) {",
      "        sorted = true;",
      "        for (int i = 1; i < n - 1; i += 2) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                std::swap(arr[i], arr[i + 1]);",
      "                sorted = false;",
      "            }",
      "        }",
      "        for (int i = 0; i < n - 1; i += 2) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                std::swap(arr[i], arr[i + 1]);",
      "                sorted = false;",
      "            }",
      "        }",
      "    }",
      "}"
    ],
    c: [
      "void oddEvenSort(int arr[], int n) {",
      "    int sorted = 0;",
      "    while (!sorted) {",
      "        sorted = 1;",
      "        for (int i = 1; i < n - 1; i += 2) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                sorted = 0;",
      "            }",
      "        }",
      "        for (int i = 0; i < n - 1; i += 2) {",
      "            if (arr[i] > arr[i + 1]) {",
      "                int temp = arr[i]; arr[i] = arr[i + 1]; arr[i + 1] = temp;",
      "                sorted = 0;",
      "            }",
      "        }",
      "    }",
      "}"
    ]
  },
  pancakeSort: {
    pseudocode: [
      "for curr_size from n to 1:",
      "  max_idx = findMax(arr, curr_size)",
      "  if max_idx != curr_size-1:",
      "    flip(arr, max_idx)",
      "    flip(arr, curr_size-1)"
    ],
    javascript: [
      "function pancakeSort(arr) {",
      "  let n = arr.length;",
      "  for (let currSize = n; currSize > 1; currSize--) {",
      "    let maxIdx = findMax(arr, currSize);",
      "    if (maxIdx !== currSize - 1) {",
      "      flip(arr, maxIdx);",
      "      flip(arr, currSize - 1);",
      "    }",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def pancake_sort(arr):",
      "    n = len(arr)",
      "    for curr_size in range(n, 1, -1):",
      "        max_idx = arr.index(max(arr[:curr_size]))",
      "        if max_idx != curr_size - 1:",
      "            arr[:max_idx + 1] = reversed(arr[:max_idx + 1])",
      "            arr[:curr_size] = reversed(arr[:curr_size])",
      "    return arr"
    ],
    java: [
      "public static void pancakeSort(int[] arr) {",
      "    int n = arr.length;",
      "    for (int currSize = n; currSize > 1; currSize--) {",
      "        int maxIdx = findMax(arr, currSize);",
      "        if (maxIdx != currSize - 1) {",
      "            flip(arr, maxIdx);",
      "            flip(arr, currSize - 1);",
      "        }",
      "    }",
      "}"
    ],
    cpp: [
      "void pancakeSort(int arr[], int n) {",
      "    for (int currSize = n; currSize > 1; --currSize) {",
      "        int maxIdx = findMax(arr, currSize);",
      "        if (maxIdx != currSize - 1) {",
      "            flip(arr, maxIdx);",
      "            flip(arr, currSize - 1);",
      "        }",
      "    }",
      "}"
    ],
    c: [
      "void pancakeSort(int arr[], int n) {",
      "    for (int currSize = n; currSize > 1; --currSize) {",
      "        int maxIdx = findMax(arr, currSize);",
      "        if (maxIdx != currSize - 1) {",
      "            flip(arr, maxIdx);",
      "            flip(arr, currSize - 1);",
      "        }",
      "    }",
      "}"
    ]
  },
  bitonicSortWrapper: {
    pseudocode: [
      "function bitonicSort(arr, up):",
      "  if length(arr) > 1:",
      "    m = length(arr) / 2",
      "    bitonicSort(arr[0:m], 1)",
      "    bitonicSort(arr[m:], 0)",
      "    bitonicMerge(arr, up)"
    ],
    javascript: [
      "function bitonicSort(arr, low, cnt, dir) {",
      "  if (cnt > 1) {",
      "    let k = cnt / 2;",
      "    bitonicSort(arr, low, k, 1);",
      "    bitonicSort(arr, low + k, k, 0);",
      "    bitonicMerge(arr, low, cnt, dir);",
      "  }",
      "}"
    ],
    python: [
      "def bitonic_sort(arr, low, cnt, direction):",
      "    if cnt > 1:",
      "        k = cnt // 2",
      "        bitonic_sort(arr, low, k, 1)",
      "        bitonic_sort(arr, low + k, k, 0)",
      "        bitonic_merge(arr, low, cnt, direction)"
    ],
    java: [
      "public static void bitonicSort(int[] arr, int low, int cnt, int dir) {",
      "    if (cnt > 1) {",
      "        int k = cnt / 2;",
      "        bitonicSort(arr, low, k, 1);",
      "        bitonicSort(arr, low + k, k, 0);",
      "        bitonicMerge(arr, low, cnt, dir);",
      "    }",
      "}"
    ],
    cpp: [
      "void bitonicSort(int arr[], int low, int cnt, int dir) {",
      "    if (cnt > 1) {",
      "        int k = cnt / 2;",
      "        bitonicSort(arr, low, k, 1);",
      "        bitonicSort(arr, low + k, k, 0);",
      "        bitonicMerge(arr, low, cnt, dir);",
      "    }",
      "}"
    ],
    c: [
      "void bitonicSort(int arr[], int low, int cnt, int dir) {",
      "    if (cnt > 1) {",
      "        int k = cnt / 2;",
      "        bitonicSort(arr, low, k, 1);",
      "        bitonicSort(arr, low + k, k, 0);",
      "        bitonicMerge(arr, low, cnt, dir);",
      "    }",
      "}"
    ]
  },
  radixSort: {
    pseudocode: [
      "for digit from LSD to MSD:",
      "  create buckets[0-9]",
      "  for each number in arr:",
      "    place in bucket by digit",
      "  collect from buckets back to arr"
    ],
    javascript: [
      "function radixSort(arr) {",
      "  let max = Math.max(...arr);",
      "  for (let exp = 1; Math.floor(max / exp) > 0; exp *= 10) {",
      "    countingSortForRadix(arr, exp);",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def radix_sort(arr):",
      "    max_val = max(arr)",
      "    exp = 1",
      "    while max_val // exp > 0:",
      "        counting_sort_for_radix(arr, exp)",
      "        exp *= 10",
      "    return arr"
    ],
    java: [
      "public static void radixSort(int[] arr) {",
      "    int max = getMax(arr);",
      "    for (int exp = 1; max / exp > 0; exp *= 10) {",
      "        countingSort(arr, exp);",
      "    }",
      "}"
    ],
    cpp: [
      "void radixSort(int arr[], int n) {",
      "    int m = getMax(arr, n);",
      "    for (int exp = 1; m / exp > 0; exp *= 10) {",
      "        countingSort(arr, n, exp);",
      "    }",
      "}"
    ],
    c: [
      "void radixSort(int arr[], int n) {",
      "    int m = getMax(arr, n);",
      "    for (int exp = 1; m / exp > 0; exp *= 10) {",
      "        countingSort(arr, n, exp);",
      "    }",
      "}"
    ]
  },
  stoogeSortWrapper: {
    pseudocode: [
      "function stoogeSort(arr, i, j):",
      "  if arr[i] > arr[j]: swap(arr[i], arr[j])",
      "  if j - i + 1 > 2:",
      "    t = (j - i + 1) / 3",
      "    stoogeSort(arr, i, j-t)",
      "    stoogeSort(arr, i+t, j)",
      "    stoogeSort(arr, i, j-t)"
    ],
    javascript: [
      "function stoogeSort(arr, i = 0, j = arr.length - 1) {",
      "  if (arr[i] > arr[j]) [arr[i], arr[j]] = [arr[j], arr[i]];",
      "  if (j - i + 1 > 2) {",
      "    let t = Math.floor((j - i + 1) / 3);",
      "    stoogeSort(arr, i, j - t);",
      "    stoogeSort(arr, i + t, j);",
      "    stoogeSort(arr, i, j - t);",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def stooge_sort(arr, i, j):",
      "    if arr[i] > arr[j]:",
      "        arr[i], arr[j] = arr[j], arr[i]",
      "    if j - i + 1 > 2:",
      "        t = (j - i + 1) // 3",
      "        stooge_sort(arr, i, j - t)",
      "        stooge_sort(arr, i + t, j)",
      "        stooge_sort(arr, i, j - t)"
    ],
    java: [
      "public static void stoogeSort(int[] arr, int i, int j) {",
      "    if (arr[i] > arr[j]) {",
      "        int temp = arr[i]; arr[i] = arr[j]; arr[j] = temp;",
      "    }",
      "    if (j - i + 1 > 2) {",
      "        int t = (j - i + 1) / 3;",
      "        stoogeSort(arr, i, j - t);",
      "        stoogeSort(arr, i + t, j);",
      "        stoogeSort(arr, i, j - t);",
      "    }",
      "}"
    ],
    cpp: [
      "void stoogeSort(int arr[], int i, int j) {",
      "    if (arr[i] > arr[j]) std::swap(arr[i], arr[j]);",
      "    if (j - i + 1 > 2) {",
      "        int t = (j - i + 1) / 3;",
      "        stoogeSort(arr, i, j - t);",
      "        stoogeSort(arr, i + t, j);",
      "        stoogeSort(arr, i, j - t);",
      "    }",
      "}"
    ],
    c: [
      "void stoogeSort(int arr[], int i, int j) {",
      "    if (arr[i] > arr[j]) {",
      "        int temp = arr[i]; arr[i] = arr[j]; arr[j] = temp;",
      "    }",
      "    if (j - i + 1 > 2) {",
      "        int t = (j - i + 1) / 3;",
      "        stoogeSort(arr, i, j - t);",
      "        stoogeSort(arr, i + t, j);",
      "        stoogeSort(arr, i, j - t);",
      "    }",
      "}"
    ]
  },
  bogoSort: {
    pseudocode: [
      "while not isSorted(arr):",
      "  shuffle(arr)"
    ],
    javascript: [
      "function bogoSort(arr) {",
      "  while (!isSorted(arr)) {",
      "    shuffle(arr);",
      "  }",
      "  return arr;",
      "}"
    ],
    python: [
      "def bogo_sort(arr):",
      "    while not is_sorted(arr):",
      "        shuffle(arr)",
      "    return arr"
    ],
    java: [
      "public static void bogoSort(int[] arr) {",
      "    while (!isSorted(arr)) {",
      "        shuffle(arr);",
      "    }",
      "}"
    ],
    cpp: [
      "void bogoSort(int arr[], int n) {",
      "    while (!isSorted(arr, n)) {",
      "        shuffle(arr, n);",
      "    }",
      "}"
    ],
    c: [
      "void bogoSort(int arr[], int n) {",
      "    while (!isSorted(arr, n)) {",
      "        shuffle(arr, n);",
      "    }",
      "}"
    ]
  }
};

export const sortingExamples: Record<string, string> = {
  bubbleSort: "A teacher physically sorting a row of students by height by swapping two adjacent standing students until they are aligned from shortest to tallest.",
  selectionSort: "A card player selecting the lowest value card from their hand, swapping it with the first card, then repeating for the remaining cards.",
  insertionSort: "Sorting a hand of playing cards: you pick up a card from the table, compare it to cards already in your hand, and slide it directly into its sorted spot.",
  mergeSortWrapper: "E-Commerce sites sorting millions of items by 'Rating' and then 'Price'. Because Merge Sort is stable, sorting by price preserves the rating order.",
  quickSortWrapper: "Organizing files inside a hard drive database index or sorting in-memory system arrays inside highly optimized codebases like V8.",
  heapSort: "An operating system executing CPU tasks where the task with the highest priority must always be popped out first in O(1) time.",
  shellSort: "Sorting inventory counts in a low-resource smart thermostat or IoT device with only 2KB of RAM, where Quick Sort's recursion would overflow memory.",
  cocktailSort: "Tidying a bookshelf where almost all books are sorted, but a few heavy textbooks at the end need to travel back to the beginning of the shelf.",
  combSort: "Cleaning up sensor logging datasets on low-power microcontrollers before transmitting data packets to a central server.",
  gnomeSort: "A garden gnome walking to the next flowerpot, comparing it with the previous, swapping them if needed, and stepping back to verify ordering.",
  oddEvenSort: "A parallel GPU sorting block where adjacent elements at odd/even pixel locations are processed simultaneously across 1000 rendering cores.",
  pancakeSort: "A sorting machine stacker adjusting a pile of heavy wooden pallets by slipping a forklift under a segment and flipping the sub-stack over.",
  bitonicSortWrapper: "An FPGA graphics acceleration card running a network of wire comparisons in parallel blocks for real-time video buffer stream sorting.",
  radixSort: "Sorting a mailing list of 100,000 envelopes by their 5-digit ZIP codes, sorting them first by the 5th digit, then the 4th, up to the 1st digit.",
  stoogeSortWrapper: "Used as a theoretical warning example in computer science textbooks to show how recursion can go disastrously wrong.",
  bogoSort: "Sorting a deck of cards by throwing them in the air, picking them up randomly, and checking if they landed in perfect sorted order."
};
